### ISSUE TITLE
Warnings and Errors on the console

### ISSUE THREAD

**Issue by af7** [wwayne/react-tooltip#10]
While I managed to get the Tooltip on a page element, I do get the following warnings/errors on the console:

![image](https://cloud.githubusercontent.com/assets/7850073/7881025/910b3cb0-0607-11e5-8acb-75cfe7ddf08b.png)

Do you have an idea why this may be happening?

Thanks.

**Comment by wwayne** [comment]
It more like you miss some components in you app instead of caused by react-tooltip, like missing <tbody> in <table>.
It would be better if you can give me more information.

**Comment by af7** [comment]
Ok, I don't have the error now, I made some changes. But I have the warning. What does this warning mean?

**Comment by wwayne** [comment]
No idea, but I think you should check your `React.render(ReactComponent, targetElement)`, maybe the `targetElement` has been removed when you setState
