### ISSUE TITLE
Multiple data-event options

### ISSUE THREAD

**Issue by cristina-hgdata** [wwayne/react-tooltip#111]
Is it possible to use this tooltip component and have it open on click and also on focus? i.e. data-event="click focus"

**Comment by wwayne** [comment]
I think it is possible, I can try to add this feature in the feature

**Comment by cristina-hgdata** [comment]
I tried adding `data-event="click focus"` but the tooltip doesn't appear at all

**Comment by wwayne** [comment]
the tooltip doesn't support multiple event at the moment, so it can't recognize `click focus`

**Comment by cristina-hgdata** [comment]
Thanks

**Comment by wwayne** [comment]
I don't think this is useful, closing for now until more people ask for this

**Comment by abijames** [comment]
I need multiple events in order to use react-tooltip. I am looking for an accessible tooltip solution that will active both for mouse and keyboard users so that the tooltip appears when the user tabs to an item to give it focus or if they hover with the mouse.

**Comment by wwayne** [comment]
Supported in 3.0.0
