### ISSUE TITLE
triangle has low resolution

### ISSUE THREAD

**Issue by Moezalez** [wwayne/react-tooltip#114]
![screen shot 2016-06-15 at 14 34 50](https://cloud.githubusercontent.com/assets/8615251/16079946/67a27fdc-3306-11e6-87b6-6ed7536d8b5c.png)

Seems only to affect this component, everything else looks smooth.

**Comment by wwayne** [comment]
I think this is related to the screen resolution, I checked it carefully in a retina screen and a non-retina screen, it's okay.
