### ISSUE TITLE
3.0.4 fails as npm dependency when trying to build app

### ISSUE THREAD

**Issue by dysfunc** [wwayne/react-tooltip#118]
Not sure if others are seeing this but having issues with 3.0.4. I downgraded to 3.0.0 and everything was fine.

**Comment by wwayne** [comment]
@dysfunc I should have fixed this yesterday, I just tested 3.0.4 and it works, simplified code is like following:
```
import ReactTooltip from 'react-tooltip'

class Test extends Component {
 render () {
     <div>
         <p data-tip='test'>test</p>
        <ReactTooltip />
     </div>
  }
}
```
