### ISSUE TITLE
use data-event-off='click' on <ReactTooltip> 

### ISSUE THREAD

**Issue by YeZhiqiuSev** [wwayne/react-tooltip#123]
I use default settings of tooltip,but the tip was not disappear sometime when I click the icon.

hover or focus the icon ,it shows:
![screen shot 2016-06-24 at 10 17 54](https://cloud.githubusercontent.com/assets/18155748/16325948/0db61a24-39f5-11e6-99b9-e8b1c2d3f2b5.png)

then click the icon in:
![screen shot 2016-06-24 at 10 18 04](https://cloud.githubusercontent.com/assets/18155748/16325962/1e7e423c-39f5-11e6-8810-b90102441966.png)
 
It was not disappear, untill I scroll my mouse or return to the last page and hover out the icon.

what's the problem?

**Comment by wwayne** [comment]
Could you give me the related code please?

**Comment by YeZhiqiuSev** [comment]
well, In the package json  that's ```javasript  "react-tooltip": "^1.1.4", ```.And on the page, that's ```javascript  <a className="cq-icon icon-compare-2-1 margin-right-sm"
                        onClick={this.handleSelectCompareAppClick(app.x)}
                        data-tip="ASO对比" />```
use data-tip ,very normal usage. what's the problem?

**Comment by YeZhiqiuSev** [comment]
well, In the package json that's ```javascript
 "react-tooltip": "^1.1.4"```.
And on the page, that's ```javascript <a className="cq-icon icon-compare-2-1 margin-right-sm" onClick={this.handleSelectCompareAppClick(app.x)} data-tip="ASO对比" />```
use data-tip ,very normal usage. what's the problem?

**Comment by YeZhiqiuSev** [comment]
well, In the package json that's ```javascript
 "react-tooltip": "^1.1.4"
```
And on the page, that's 
```javascript <a className="cq-icon icon-compare-2-1 margin-right-sm" onClick={this.handleSelectCompareAppClick(app.x)} data-tip="ASO对比" />
```
use data-tip ,very normal usage. what's the problem?

**Comment by YeZhiqiuSev** [comment]
well, In the package json that's "react-tooltip": "^1.1.4 version.
And the html clip is  <a className="cq-icon icon-compare-2-1 margin-right-sm" onClick={this.handleSelectCompareAppClick(app.x)} data-tip="ASO对比" />
using data-tip attribute , very normal usage. what's the problem?

**Comment by wwayne** [comment]
@YeZhiqiuSev First you can try to update the react-tooltip to the latest version, then you should use eventOff instead of data-event-off on ReactTooltip `<ReactTooltip eventOff='click'/>`.

**Comment by YeZhiqiuSev** [comment]
That's doesn't make any sense. And I find a new problem is everything goes well when the first click on the page(the page was just be refreshed).But the second click will be failed.

**Comment by wwayne** [comment]
@YeZhiqiuSev Looks you only set the `eventOff` attribute? At the moment, `eventOff` only makes effect after setting `event`, sounds a bit unreasonable, I can change later.

And it would better if you can give more details of the code, currently I can' figure out how you use the react-tooltip. Since you have given me the tip setting on the target element, I would like to know what attributes you set on `<ReactTooltip />` and what does `handleSelectCompareAppClick` used for.

**Comment by YeZhiqiuSev** [comment]
Sounds like some troublesome. Finally I called the manually function ReactTooltip.hide() in my click function and solve this problem temporary.

**Comment by wwayne** [comment]
Okay, or you can try ReactTooltip.rebuild() to re-bind the tooltip, closing
