### ISSUE TITLE
Error: Cannot resolve module 'react-tooltip'

### ISSUE THREAD

**Issue by przemuh** [wwayne/react-tooltip#133]
Hi,

I try to use React-Tooltip with webpack and ES6 modules. After positive installation from npm I try to include the tooltip in my React-Redux app:

```
import ReactTooltip from "react-tooltip";

const App = ({ store }) => (
    <Provider store={ store }>
        <Wrapper>
            <Header />
            <ConnectedViewWrapper />
            <ReactTooltip />
        </Wrapper>
    </Provider>
);

export default App;
```

During the build process I get an error:

```
ERROR in ./src/main/javascript/app/App.jsx
Module not found: Error: Cannot resolve module 'react-tooltip' 
```

Quick solution: change the package.json of react-tooltip (because dist folder is missing):

```
  "main": "standalone/react-tooltip.js",
```

But then I get:

```
WARNING in ./~/react-tooltip/standalone/react-tooltip.js
Critical dependencies:
1:485-492 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-tooltip/standalone/react-tooltip.js 1:485-492
```

And when my app is running the error in console appears:

```
react-tooltip.js:693 Uncaught TypeError: Cannot read property 'Component' of undefined
```

I've tried using (node 4.4.7 + npm 2.15.8)  and  (6.3.0 + 3.10.3) - no difference

Thanks in advance for any help.

**Comment by wwayne** [comment]
@przemuh I made a stupid mistake, I didn't push `dist/` to npm... plz try `3.0.10`

**Comment by przemuh** [comment]
Now works like a charm :) Thanks !

**Comment by whitehorse0324** [comment]
I see this problem, too.
My npm version is 7.8.0
The version of react-tooltip is 4.2.17

Can you help me?
