### ISSUE TITLE
Tooltip not shown sometimes

### ISSUE THREAD

**Issue by donilan** [wwayne/react-tooltip#134]
When there is a element that using a variable for content of tooltip and the variable is null first, then the tooltip will not shown, for example below.

```javascript
render() {
  let disabled = this.whatEveryFunction();
  let tip = disabled ? 'Show something' : null;
  return (
    <div>
      <p data-tip="always show something"></p>
      <button data-tip={tip}>Save</button>
      <ReactTooltip />
    </div>
  )
}
```

**Comment by donilan** [comment]
It will works if I change null to empty string, is it a bug or something?

**Comment by wwayne** [comment]
@donilan that's because the tooltip only accept String

**Comment by asidiali** [comment]
@donilan you can also call `ReactTooltip.rebuild()` to re-bind tooltips. I'm using this in a `componentDidUpdate` hook to re-bind tooltips as data changes.

**Comment by Chetan11-dev** [comment]
@asidiali  is Correct Snippet 
```
    useEffect(() => {
        ReactTooltip.rebuild()
    });

```
