### ISSUE TITLE
Listen to body mouseover/mouseout rather than on individual elements?

### ISSUE THREAD

**Issue by mattzeunert** [wwayne/react-tooltip#137]
It looks like the event listeners are added to each `[data-tip]` element when the ReactTooltip component mounts. That means I have to manually rebuild the bindings when the UI changes.

Would it be possible to add a mouseover listener to the body and then check if the event target element has a `data-tip` attribute?

**Comment by wwayne** [comment]
It could be a solution, but not sure if it would have some other side effects, will make experiments later.

**Comment by oyeanuj** [comment]
Also interested in this!

**Comment by brafdlog** [comment]
This is a significant issue.
In the current implementation if an element is rendered after the componentDidMount of the ReactTooltip component, the tooltips on it wont work.
Calling rebuild is not a solution becuase I need to know to call rebuild anywhere there might be a tooltip, and rebuild is quite heavy - calling it on every render will eventually crash the browser tab.
@wwayne what do you think?

**Comment by lanjingling0510** [comment]
Having the same issue. Dynamic elements have not come out, document.querySelectorAll not get data-tip elements, resulting in tooltip not come out.
