### ISSUE TITLE
Tooltip jitters on mousemove when effect is "solid"

### ISSUE THREAD

**Issue by mattzeunert** [wwayne/react-tooltip#138]
On mousemove it seems like the right edge of the div is moving by 1px.

![react-tooltip-jitter](https://cloud.githubusercontent.com/assets/1303660/16896295/5b9a2a8e-4b87-11e6-9bfb-c1924a96ef16.gif)

**Comment by wwayne** [comment]
Same with https://github.com/wwayne/react-tooltip/issues/51

**Comment by wwayne** [comment]
I've tested it with two different macbook, one is non-retina, the other is retina, but I can't reproduce this....

**Comment by mir3z** [comment]
I can reproduce this on Ubuntu 14.04 with nouveau driver, Chrome Version 49.0.2623.87 (64-bit)

**Comment by johnny353535** [comment]
I can reproduce it in Chrome 51, external non-retina monitor. I'm on OSX Yosemite on a Macbook Pro.

**Comment by wwayne** [comment]
Should be fixed in `3.1.0`
