### ISSUE TITLE
Tooltip jumps/shakes in Solid state

### ISSUE THREAD

**Issue by rickitan** [wwayne/react-tooltip#146]
Hi @wwayne, 

I found the following issue when using the solid effect and positioning bottom/top: 

![react-tooltip](https://cloud.githubusercontent.com/assets/3137417/17137948/e5085f6c-530b-11e6-8c2f-092dafc472b4.gif)

I was able to reproduce it on the demo page. The left position value keeps jumping from 397.5px to 398px and back when I'm hovering over the element. I'm currently looking for a solution. 

I suspect it might be a float precision problem with one of the calculations. Any input? 

Thanks, 

-Ricardo.

**Comment by wwayne** [comment]
I think you are right, I did some fix and released `3.1.0`

**Comment by wwayne** [comment]
Forget to say thank you, I misunderstood this as a screen problem for a long time
