### ISSUE TITLE
getPosition.js:35 Uncaught TypeError: Cannot read property 'l' of undefined

### ISSUE THREAD

**Issue by maullerz** [wwayne/react-tooltip#150]
Getting this error on quite simple example

`getPosition.js:35`

```
  // Get the edge offset of the tooltip

  var getTipOffsetLeft = function getTipOffsetLeft(place) {
    var offset_X = defaultOffset[place].l;
    return mouseX + offset_X + extraOffset_X;
  };
```

My jsx:
```
<ReactTooltip
  id='main-menu'
  place='right'
  effect='solid'
/>

<div data-tip='Видео' data-for='main-menu' />
<div data-tip='Проекты' data-for='main-menu' />
<div data-tip='Правообладатели' data-for='main-menu' />
```

On first hover on bottom menu element all is OK
![11](https://cloud.githubusercontent.com/assets/5295025/17172990/d55ce1b4-5400-11e6-8fd4-76fad2c524bc.png)

But when i move mouse top to next element prev tooltip dont dissapear but change text and spam errors in console
![22](https://cloud.githubusercontent.com/assets/5295025/17172993/d77a463a-5400-11e6-9cba-09d160331f5f.png)

![33](https://cloud.githubusercontent.com/assets/5295025/17172928/6c6389a6-5400-11e6-8c8c-834ce8f18eea.png)

**Comment by wwayne** [comment]
Fixed and released 3.1.1
