### ISSUE TITLE
can i toggle the modal from an external class/method?

### ISSUE THREAD

**Issue by virgenherrera** [wwayne/react-tooltip#154]
previously i have setted up the modal and everythig worked well, but now that my partners have implemented redux i must make the tooltip toggle from an external class, that class is the reducer class. e.g.

reducer > grandpaClass > FatherClass > classToImplementTheTooltip.

so anyone have the aswer for this question?

remember the tooltip is working well, the issue is, how to toggle it from reducer class, and how to send it properly to the destiny class.

**Comment by wwayne** [comment]
Can you show some detail of your code? especially the `classToImplementTheTooltip ` and how you implement the toggle.

I don't know if you are asking a Redux problem, but for `how to send it properly to the destiny class`, you can send it through props, for example:
```
In Reducer class
<div>< GrandpaClass foo='xxx' />  </div>

in GrandpaClass
you can get it from `this.props.foo`
```
