### ISSUE TITLE
Where to put ReactTooltip

### ISSUE THREAD

**Issue by timothyarmes** [wwayne/react-tooltip#156]
Hi,

I want to be able to put `data-tip` all over my code, so I've tried having a single `<ReactTooltip />` at the top level of my layout. This doesn't work however, since it does dynamically refresh when the page changes.

What should I be doing? Should I have a new <ReactTooltip /> in every component that includes a `data-tip`?

**Comment by wwayne** [comment]
1. You can put ReactTooltip in your every component, remember give their unique id
2. Call `ReactTooltip.rebuild()` after component fresh

I know it may sounds inconvenient, so the tooltip may change its implementation in the future https://github.com/wwayne/react-tooltip/issues/137

**Comment by h8rry** [comment]
You put <ReactTooltip /> at the top level of your layout and call `ReactTooltip.rebuild()` on `componentDidUpdate`.
