### ISSUE TITLE
Callbacks onShow & onHide

### ISSUE THREAD

**Issue by pokidovea** [wwayne/react-tooltip#157]
Hi!
Is it possible to provide callbacks for show and hide events?

**Comment by wwayne** [comment]
Yes it is possible I think, may need to further investigate

**Comment by wwayne** [comment]
Supported in 3.1.4, use `afterShow` and `afterHide` to add your callback function, e.g:
```
<ReactTooltip afterShow={() => { console.log('called after show') }} / >
```

**Comment by pokidovea** [comment]
Thanks!!!
