### ISSUE TITLE
attributes

### ISSUE THREAD

**Issue by oszkarjona-tradedoubler** [wwayne/react-tooltip#159]
Hi,
Is it possible to set attributes like role or aria-* on ReactTooltip?
THX

**Comment by wwayne** [comment]
I think it is possible, but need update the tooltip component, the tooltip component will generate a `<div></div>` actually, so we just expose an endpoint on ReactTooltip that can set aria-* on that div element

**Comment by wwayne** [comment]
Supported in 3.1.4, you can add `<ReactTooltip aria-value="xxx" role="xxx" />` for example

**Comment by oszkarjona-tradedoubler** [comment]
cool 👍

**Comment by daceynolan** [comment]
@wwayne I see that this was updated to support value and role. However, when using the screenreader, my aria-value is never being announced and the role is making it announced constantly. Do you have a workaround to get this to work with screenreaders?
