### ISSUE TITLE
React tooltip on dynamic HTML

### ISSUE THREAD

**Issue by GeniusStorm** [wwayne/react-tooltip#160]
HI have some HTML coming in from my backend That I am rendering in the React component. Its basicallya hyperlink. I have a requirement where in I have to display a tooltip text when the user hovers over the hyper link.

The issue is if I set the tooltip via setAtrribute and then try to render the reacttool tip it doesnt seem to work Is there a workaround for this?

in My component render I have this
```
  render(){
    return( 
      <div>
      <p 
        className={this.props.className} 
        dangerouslySetInnerHTML={{__html: this.props.somelink && this.props.somelink}}
        >
        <ReactTooltip type="info"></ReactTooltip>
      </p>
      </div>
    )
  }
```

This is the link coming in from the DB
`<a class="somelink"  data-title="click_me">Click me</a>
`
And this is the function that sets the data-tip attribute to this link

```
export function setToolTip(){
  let someLink = document.getElementsByClassName("somelink")[0]
  if(someLink){
      someLink.setAttribute("data-tip", 'some tip')
  }
}
```

**Comment by wwayne** [comment]
I think you can use ReactTooltip.rebuild in your setTooltip function:
```
import ReactTooltip from 'react-tooltip'

export function setToolTip(){
  let someLink = document.getElementsByClassName("somelink")[0]
  if(someLink){
      someLink.setAttribute("data-tip", 'some tip')
      ReactTooltip.rebuild()
  }
}
```I think you can use ReactTooltip.rebuild in your setTooltip function:
```
import ReactTooltip from 'react-tooltip'

export function setToolTip(){
  let someLink = document.getElementsByClassName("somelink")[0]
  if(someLink){
      someLink.setAttribute("data-tip", 'some tip')
      ReactTooltip.rebuild()
  }
}
```

**Comment by GeniusStorm** [comment]
That is what I was looking for
