### ISSUE TITLE
Tooltip with delayShow is not disappearing

### ISSUE THREAD

**Issue by caesarsol** [wwayne/react-tooltip#163]
Hello, 
the tooltip is not disappearing if the mouse is off the target when the delayShow triggers.
(#158 fixed only the console error, but not the unintended behavior)

Steps to reproduce:

1. mouseOver on a target element with a `delayShow > 0`
2. mouseOut when the tooltip has not yet appeared
3. after the `delayShow` the tooltip appears and remains visible since the mouse is not on the target element.

**Comment by caesarsol** [comment]
After further investigation, it appears that a workaround to use `delayShow` is setting a `delayHide={1}`, because this causes a reset of the Show timeout on mouseLeave.

https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L285

Moving `this.clearTimer()` outside the `if` could fix the issue @wwayne?

**Comment by wwayne** [comment]
Thanks for pointing out the bug, this should be fixed in `3.1.3`
