### ISSUE TITLE
when form input is in bootstrap modal dialog, tooltip's position and size show wrong

### ISSUE THREAD

**Issue by shupeipei** [wwayne/react-tooltip#17]
I toggle a bootstrap modal dialog, in this dialog, there is a form with inputs, some inputs have tooltip, but when i tested, tooltip element shows away from input and shows perpendicular.
when this form not in a modal dialog, the tooltip is normal
![66e13d9d-031a-4901-873e-400d29d3eaf8](https://cloud.githubusercontent.com/assets/12183336/8281350/960855e8-1919-11e5-8a49-d3f7cbec6be4.png)

**Comment by wwayne** [comment]
I've update tooltip for conditional rendering in 0.3.1, let me know if you still have problem, thanks :)

**Comment by shupeipei** [comment]
I've update tooltip to 0.3.2, i'm sorry to tell you the problem still exists.
Can i set tooltip's position for each input,
I see the example on github page like this:
         data-position="{'top': 10, 'left': 10}"
but when i try like this, the following js exception appear
![1f314963-ffd2-4df3-8f15-da16b7636bcc](https://cloud.githubusercontent.com/assets/12183336/8297630/bc9a44b4-1991-11e5-81d4-c13cbe23742b.png)

**Comment by wwayne** [comment]
Yes, you can set position like this, I will check this later.
Can you give me your code about how to use the tooltip so that I can figure out what happened ?

**Comment by shupeipei** [comment]
this is my form component:
![6dfec697-07c3-4f94-aabd-721561cdee70](https://cloud.githubusercontent.com/assets/12183336/8298003/a0ae7230-1995-11e5-9747-1f19ecaa0d83.png)

this form is included in a react-bootstrap's modal:
![ecb2c135-15d2-4612-b902-90f672a3996b](https://cloud.githubusercontent.com/assets/12183336/8298017/da8d363a-1995-11e5-81d7-b20e98a87149.png)

and this modal is an attribute for an react-bootstrap component named ModalTrigger
![a912662f-96fa-42c6-98a8-ee68144332ba](https://cloud.githubusercontent.com/assets/12183336/8298041/198ba47a-1996-11e5-9339-fce6e98f498e.png)

if you need more information, tell me, thanks

**Comment by shupeipei** [comment]
Can i know this issue processing schedule, because if this issue can't be fixed, we must find another way, i'm short on time

**Comment by wwayne** [comment]
@shupeipei 
ok, I will try sth to fix this before tonight and let you know the result.
Sorry for busy with other things these days.

**Comment by wwayne** [comment]
@shupeipei 
Position 那个我修复了，但是你项目的这个问题貌似不是bug，我是觉得这里不应该用我这个库。

我的理解: 你是希望在blur的时候对input检查，如果empty了，有个tooltip针对那个input报错。但我这个库设计之初的目的是鼠标移上去然后显示一些附加信息，所以这里应该不适合使用，不妨做成这样的警示？
![2015-06-25 21 31 02](https://cloud.githubusercontent.com/assets/5305874/8355383/8ffe1a06-1b81-11e5-8a64-d2529eb6960b.png)

然后我也很好奇 constructor(): void {} 是玩的哪一出....我都是constructor() {}这样写，跪求出处

**Comment by shupeipei** [comment]
@wwayne 
position 那个修复了或许也可以用，因为我们这个项目比较特殊，可以使用固定位置
至于 :void 这个写法是 flow 针对 js 函数的参数和返回值类型的一些检查，具体的参照 flow 官网： http://flowtype.org/

**Comment by shupeipei** [comment]
@wwayne 
我的确是在 blur 某个 input 之后针对这个 input 作检查，如果验证不通过，input 的样式会做些改变，在鼠标再次移动到 input 上的时候用 tooltip 的方式来显示错误信息
目前这个库在平常的表单中可以正常使用，tooltip 会显示到 input 旁边的位置，但是把表单放到 bootstrap 的 modal（bootstrap利用 jquery 实现的弹出框）中时 tooltip 显示的位置不正常，有比较大的偏离
你朝着这个方向看看能不能解决，毕竟用 react 之后再用原生的一些东西还是有那么点不方便的，react-bootstrap 什么的应该比较常用，这种情况怕是不会少，要是能解决总归是可以省不少事的

**Comment by wwayne** [comment]
@shupeipei 原来如此，长见识了, 谢谢 : )
行啊，我主要也没用过react-bootstrap, 我这两天(很可能是这周末)针对 react-bootstrap的modal再做个测试，短期你要来不及的话就先不要用这个tooltip了吧，实在抱歉...

我们在上海差不多每两个月有个js聚会什么的，有空的话也可以一起来交流一下啊 http://www.meetup.com/Shanghai-JavaScript-Meetup/

**Comment by wwayne** [comment]
I set the `z-index` of tooltip to 999 in case it being covered, then put <ReactTooltip /> out of <Modal /> can solve this problem
