### ISSUE TITLE
ie9下有问题

### ISSUE THREAD

**Issue by inuyasha0618** [wwayne/react-tooltip#175]
你好，ie9下出了问题，在getPosition.js文件中，第305行
while (currentParent) {
      if (currentParent.style.transform.length > 0) break;
      currentParent = currentParent.parentElement;
 }
ie9下transform应该加前缀

**Comment by wwayne** [comment]
这个应该是因为没有把css中的transform属性计算进去导致的，现在用了`getComputedStyle` 会同时顾及到inline和css，测试了下有前缀也会被计算进去应该
