### ISSUE TITLE
Pass event to `getTooltip`

### ISSUE THREAD

**Issue by astrauka** [wwayne/react-tooltip#191]
Hello @wwayne, 
I want to add react-tooltip to github like calendar heatmap - http://patientslikeme.github.io/react-calendar-heatmap/

Instead of having plenty of `ReactTooltip` components I want to have one:
```
<ReactTooltip
  id='heatmapTooltip'
  getContent={event => <div>{event.target.attributes.title.value}/>}
/>
```
Is that possible?

**Comment by wwayne** [comment]
Hi @astrauka , no sorry, I don't find any way that can meet your requirement unless you can set `attributes.title.value` to every element. For example:
```js
<div>
   <p data-tip={attributes.title.value}></p>
   <p data-tip={attributes.title.value}></p>
</div>
<ReactTooltip />
```

**Comment by astrauka** [comment]
Ok, thank you @wwayne , I went with storing hovered element id in `window` which is not clean but it works
