### ISSUE TITLE
ReactTooltip.show() does not work

### ISSUE THREAD

**Issue by ibc** [wwayne/react-tooltip#199]
> ### ReactTooltip.show(target)
>
Show specific tooltip manually, for example:
>
```js
import {findDOMNode} from 'react-dom'
import ReactTooltip from 'react-tooltip'
>
<p ref='foo' data-tip='tooltip'></p>
<button onClick={() => { ReactTooltip.show(findDOMNode(this.refs.foo)) }}></button>
<ReactTooltip />
```

This produces a `<div class="__react_component_tooltip place-top type-dark" ...>` with CSS `visibility:hidden` and `opacity:0`, which is of null use.

**Comment by wwayne** [comment]
Sorry what do you mean? I tested, I think it works, click the button and show the tooltip, so what's the problem you are meeting with?

**Comment by ibc** [comment]
In my code I didn't call `ReactTooltip.show()` within a click event, but programmatically when `componentWillReceiveProps` is called (in some cases).

Unfortunately I'm not currently using this lib so I cannot check it any more. Feel free to close the issue and thanks a lot.

**Comment by michael-go** [comment]
I stumbled upon the same problem when I called `ReactToolTip.show()` from `componentDidMount()` of the parent component, what eventually helped it work, is that I called it inside a `window.setTimeout`
