### ISSUE TITLE
Tooltip invisible when absolute positioning <div data-tip>

### ISSUE THREAD

**Issue by brian-of-nazareth** [wwayne/react-tooltip#204]

**Comment by wwayne** [comment]
Yeah react-tooltip makes use of `fixed` for positioning, why you want to add `absolute` attribute to the tooltip?

**Comment by hmeerlo** [comment]
@brian-of-nazareth is referring to absolute positioning of the div that triggers the tooltip, not the tooltip itself. I have the same problem.
