### ISSUE TITLE
Render tooltip children with passed data

### ISSUE THREAD

**Issue by frsv** [wwayne/react-tooltip#205]
Hi, I have an application with table of users, where every row has their own tooltip
So I inserted ReactTooltip component in my table-wrapper component and now I'm just wondering if there is a way to pass row props to ReactTooltip? I need this because of tooltip has custom html (so it has children in props), but this html significantly depends on the given data (for example, different images for users with different permissions)

I have table component looks like this:

```
<Table>
   <MembersTableHead
      {... headProps}
   />
   {membersList()} // array of <MembersTableItem>
   <ReactTooltip id="membersNameTooltip">
      <p> Current user: </p>
      <div>{attrs.fullName}</div> // given data
      <div>{attrs.role}</div>
      <img src={attrs.role_icon} />
      // ...etc
   </ReactTooltip>
</Table>
```

And in the MembersTableItem I want to use tooltip like this:

```
<div data-tip={props} data-for="membersNameTooltip">
   <div>{props.name}</div>
   <div>{props.role}</div>
</div>
```

I'd looked over documentation and source code and haven't found any example. Is it possible to pass data to tooltip component?

**Comment by wwayne** [comment]
Hm no there's no way to pass pros for the moment, maybe you can try to give every MembersTableItem a tooltip
```
<div data-tip={props} data-for='membersNameTooltip-1'>
   <div>{props.name}</div>
   <div>{props.role}</div>
</div>
<ReactTooltip id='membersNameTooltip-1'>{}</ReactTooltip>
```
Not sure it is make sense for you, I will think about it
