### ISSUE TITLE
Multiline tooltip

### ISSUE THREAD

**Issue by chroth7** [wwayne/react-tooltip#21]
Hi. Thanks for the nice component. I was playing with it a bit and sadly couldn't find a way to do multiline tooltips, like:

foo
bar

Is there a quick way to get that? Thanks!
(I quickly checked the source, but couldn't find any)

**Comment by wwayne** [comment]
@chroth7 
No, currently can not support this

**Comment by chroth7** [comment]
@wwayne thanks for quick feedback! 
Feel free to close this issue if you want to.
