### ISSUE TITLE
getContent to be called on re-render

### ISSUE THREAD

**Issue by mox-1** [wwayne/react-tooltip#214]
Hi,

I have a use-case whereby a tooltip has dynamically generated content received from the server. The request for content is triggered by the initial tooltip trigger event. When content is received, props change, re-render occurs... but getContent is not called unless another trigger event is called. Ideally the user could see this content without having to re-hover over the tooltip, as is currently the default case. Is there a workaround for this that I am not aware of?

**Comment by wwayne** [comment]
Well, sorry no, I can't think out other solution for this scenario.
getContent is just a function, it's not involved in the react lifecycle, so technically, it won't work.

**Comment by jeanmichelcote** [comment]
Just try to add the static method `ReactTooltip.rebuild()` in your `componentDidUpdate` lifecycle hook, like so:

```
componentDidUpdate() {
  if (this.props.myTooltipData !== prevProps.myTooltipData) {
    ReactTooltip.rebuild();
  }
}
```

Worked for me.
