### ISSUE TITLE
Solid tooltip doesn't scroll with source

### ISSUE THREAD

**Issue by zekedroid** [wwayne/react-tooltip#221]
It looks like when the `event="click"`, the tooltip stays fixed on the screen rather than move with the component:

![tooltip-test](https://cloud.githubusercontent.com/assets/3967230/19941925/607c6202-a108-11e6-8c73-65b0e8bb8843.gif)

Same component without the event (meaning it comes up on hover) working fine on scroll:

![tooltip-test-hover](https://cloud.githubusercontent.com/assets/3967230/19941965/7d01c03e-a108-11e6-9079-0297acb1fdab.gif)

It seems like when the tooltip is activated on click it's setting the display to `fixed` or something that no longer allows scroll to work correctly. Is there a workaround or is this a bug?

**Comment by wwayne** [comment]
Yes, it is intended. Basically, I remember it's hard(or impossible) to set float tooltip for custom event

**Comment by essaji** [comment]
This is still an issue for me
