### ISSUE TITLE
Using data-event: click gives errors when using component in react/angular setup

### ISSUE THREAD

**Issue by pwistbac** [wwayne/react-tooltip#224]
I am getting this error when using the data-event property (using the example given on http://wwayne.com/react-tooltip/). 

TypeError: Cannot read property '_bound' of undefined

My setup is probably at fault, because i am using react with angular 1 (ngReact).

The error traces back to line 26 in customEvent.js where the variable customListener is undefined 
ele.removeEventListener(event, customListener);
The error then traces to zone.js line 946 where the 'fn' parameter in 
obj.removeEventListener = function (eventName, fn) is undefined.

I removed this line in customEvent.js and everything seems to work. Do you know what the problem might be?
Thank you

**Comment by wwayne** [comment]
No, I haven't met an error with such error message, what custom event you've added to the tooltip?

**Comment by pwistbac** [comment]
I was binding the click event

**Comment by wwayne** [comment]
okay, I thought you are using some other custom events, well sorry I don't know the reason
