### ISSUE TITLE
New Feature: Pass array of places instead of string

### ISSUE THREAD

**Issue by hurrtz** [wwayne/react-tooltip#225]
Hi,

I have to implement a scenario in which the tooltip has to be placed right or left (depending on available space) of a large column. On very large screens there is a chance that the tooltip gets placed on top or at the bottom, whereas, as I mentioned, only left or right should be ok.

How about giving the user the option to pass an array of valid places instead of the current string?
Specifically I think of something like this:

`place: _react.PropTypes.oneOf(_react.PropTypes.string, _react.PropTypes.array)`

This would solve my issue. Not sure, though, how many people would benefit from this feature...

**Comment by wwayne** [comment]
Hi, how about using multiline `sth <br /> sth <br />`?
