### ISSUE TITLE
the position is not right when I set css3 property transform

### ISSUE THREAD

**Issue by smancang** [wwayne/react-tooltip#228]
for example:
&lt;div class="grand-parent"&gt;
&lt;div class="side"&gt;
  &lt;a data-tip="true" data-for="sadFace" currentitem="false"&gt; இдஇ &lt;/a&gt;
  &lt;div class="__react_component_tooltip place-top type-warning " data-id="tooltip" style="left: 1087px; top: 350px;"&gt;
  &lt;span&gt;Show sad face&lt;/span&gt;
  &lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;

when I set the css

.grand-parent {
 transform: scale(1.5);
}

then the tool-tip will not be in the right place when I hover the a element.

**Comment by wwayne** [comment]
Conflict with #213, I'm gonna solve this...
