### ISSUE TITLE
Links and buttons in toolip

### ISSUE THREAD

**Issue by tdziezyk** [wwayne/react-tooltip#230]
Is it possible to add clickable buttons or links to tooltip? I add custom component with links and buttons but when I click them tooltip disappear and no action is fired. 
Could you add a demo with button/link in tooltip?

**Comment by tdziezyk** [comment]
Ok, I find a way to make link/buttons clickable :).
It needs only to override  css property.
`pointer-events: auto;`

**Comment by ruucm-working** [comment]
Yeaah, It works !
