### ISSUE TITLE
Problems in IE9: getComputedStyle causes tooltip not to show

### ISSUE THREAD

**Issue by janinel** [wwayne/react-tooltip#232]
Even using babel I have found that in IE9 window.getComputedStyle(currentParent).getPropertyValue('transform') returns ''
which causes problems in node_modules\react-tooltip\dist\utils\getPosition.js: 
```javascript
if (window.getComputedStyle(currentParent).getPropertyValue('transform') !== 'none') break;
```
and the tooltip does not show

If I change the code to 
```javascript
if (window.getComputedStyle(currentParent).getPropertyValue('transform') !== 'none' && window.getComputedStyle(currentParent).getPropertyValue('transform') !== '') break;
```
the tooltip shows

**Comment by mirovelk** [comment]
I have similar problem in phantom.js. 

I think getComputedStyle is not used correctly here. Returned object is supposed to have the number indexed values. See http://stackoverflow.com/a/36941847. So calling getPropertyValue('transform') here isn't cross browser safe. It returns null (I think) witch makes currentParent = currentTarget. 

I am not completely sure what the while loop is actually for but from now on it messes stuff up and tooltip top/left position is set way of the screen/viewport.

**Comment by mirovelk** [comment]
Btw this is my fix. Not completely sure it's 100% correct but works for me in phantom.

in src/utils/getPosition.js:
```
// Decide if element was transformed or not
const isElementTransformed = (element) => {
  const computedStyles = window.getComputedStyle(element)
  for (var prop in computedStyles) {
    if (prop === 'transform') {
      if (computedStyles['transform'] === 'none') {
        return false
      }
      return true
    }
  }
  return false
}

// Get the offset of the parent elements
const getParent = (currentTarget) => {
  let currentParent = currentTarget

  while (currentParent) {
    if (isElementTransformed(currentParent)) break
    currentParent = currentParent.parentElement
  }

  const parentTop = currentParent && currentParent.getBoundingClientRect().top || 0
  const parentLeft = currentParent && currentParent.getBoundingClientRect().left || 0

  return {parentTop, parentLeft}
}
```

**Comment by huumanoid** [comment]
Thank you guys for your fixes. Thanks @mirovelk for your investigation! It's really helpful.

It seems like the only right cross-browser safe way to check 'transform' is to parse `cssText` field of the `CSSStyleDeclaration`. I'm not sure we have to go that deep.

Perhaps the most appropriate fix is to check, if `getPropertyValue('transform')` is `'none'`, `null` or `''`. What do you guys think?

**Comment by janinel** [comment]
I think that is the pragmatic solution.
