### ISSUE TITLE
Tooltips of adjacent elements not showing

### ISSUE THREAD

**Issue by kevinlaw91** [wwayne/react-tooltip#235]
This is quite similar to #58 which was closed. Not sure if they were the same.
![adjacent](https://cloud.githubusercontent.com/assets/4179182/20977752/71beb124-bce1-11e6-8aac-d7eef6b979ab.gif)

Problem seems to be coming from [src/index.js#L222](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L222).

Removing `this.state.show` seems will fix it. Hope this helps you in debugging.
```diff
- if (!isMyElement || this.state.show) return
+ if (!isMyElement) return
```

**Comment by huumanoid** [comment]
Interesting! It seems like you are using `ReactTooltip.show` to manually show the tooltip.
`this.state.show` causes errors for my cases too.
@wwayne, please, tell us, what is it for?

**Comment by cptdesro** [comment]
@huumanoid  @kevinlaw91  @wwayne  Have you guys found a solution ? I have the same probleme ...
