### ISSUE TITLE
imports-loader dependency

### ISSUE THREAD

**Issue by FunkyloverOne** [wwayne/react-tooltip#237]
After I have installed `react-tooltip` I was receiving an error while importing `ReactTooltip`.

Here it is:
`Module not found: Error: Cannot resolve module 'imports'`

It was because I didn't have `imports-loader` package in my app dependencies and even didn't have that package installed.
I think it should be explicitly set in your `package.json` or at least mentioned in `README.md`.

**Comment by wwayne** [comment]
imports-loader is used for webpack. For react-tooltip, it doesn't use webpack and it doesn't use imports-loader as dependency

**Comment by FunkyloverOne** [comment]
@wwayne understood, thanks. Anyway it might be helpful for someone like me to mention that in readme.

**Comment by wwayne** [comment]
Hmm, maybe not, because technically it has nothing to do with this library, related knowledge should be written in Webpack docs.
