### ISSUE TITLE
Add delay on showTooltip

### ISSUE THREAD

**Issue by johnamiahford** [wwayne/react-tooltip#24]
How do we feel about adding a possible delay on showing a tooltip? 

Something along the lines of: 
```javascript
showTooltip(e) {
  if (this.props.delay) {
    return setTimeout(this.updateTooltip, this.props.delay);
  }

  // run normal update
  this.updateTooltip(e);
}
```

**Comment by wwayne** [comment]
Allow adding custom class may satisfy this kind of requirements.
I can add this in the future.
