### ISSUE TITLE
`class` prop should be renamed to a non reserved word

### ISSUE THREAD

**Issue by ricardogrw** [wwayne/react-tooltip#242]
Maybe change it to `extraClass` as you use it in your code?

Of course this is my opinion, feel free to close if needed

Also, your component is pretty awesome 😄

**Comment by wwayne** [comment]
Thanks @jonbeller , `className` option has been added and the old one `class` has been kept to compatible with previous users

**Comment by ricardogrw** [comment]
Thanks for taking care of this
