### ISSUE TITLE
Hide parent element tooltip when hover child element 

### ISSUE THREAD

**Issue by faintx4** [wwayne/react-tooltip#244]
Need help me with my problem.
I have some `<li>` element with tooltip (of course it appears when I hover this `<li>`). Also inside that `<li>` I have some `<span>` with icon inside that has tooltip as well.
The problem is: when I hover `<span>` (the child of `<li>`) the tooltip for `<li>` is still appears but I need to show only tooltip for `<span>`.
How can I fix that?

I even tried to hide parent `<li>` tooltip on mouse over but it didn't help:
`<li onClick={ setActiveDirectory }
    data-tip data-for="active-directory"
    ref="activedir"
>
  <span onClick={ (event) => changeDirectoryState(event) }
        data-tip data-for="open-directory"
        onMouseOver={() => { ReactTooltip.hide(findDOMNode(this.refs.activedir))}}
  />
</li>`

![screenshot_1](https://cloud.githubusercontent.com/assets/5254764/22015783/1c8900f2-dcac-11e6-964b-9d2b2ac00fda.png)
`

**Comment by wwayne** [comment]
@faintx4 To be honest, I didn't think about how to deal with such situation. And I don't see any good solution for the moment, I suggest you changing HTML structure to get rid of such problem or take a look at other similar react tooltip components

**Comment by faintx4** [comment]
@wwayne ok I understand. I will change HTML structure.
