### ISSUE TITLE
scrollHide not hiding tooltip on mobile

### ISSUE THREAD

**Issue by ryanhca** [wwayne/react-tooltip#248]
I'm assuming this has something to do with the "hover" event since there isn't really one in Mobile. I'm wondering if anyone else has run into this problem and come up with a solution, I don't want to have to add eventHandlers all over to capture the scroll event.

Here is an example of my code: 

    <ReactToolTip 
        multiline={true}
        scrollHide={true}
        scrollResize={true}
        class="tipOverrides"
        id={tipid}
        effect="solid"
        place='top' 
        type='info'/>

I'm trying to use the scrollHide and scrollResize events according to docs.

**Comment by philraj** [comment]
`scrollHide` is actually not working at all for me (on desktop). Are you using a single top-level `<ReactTooltip>` element?

**Comment by ajritch** [comment]
+1 to scrollHide not working (on desktop), not using a single top-level element.

**Comment by huumanoid** [comment]
Hey guys, can this issue be reproduced at the [examples page](http://wwayne.com/react-tooltip/)?
I can see that the left tooltip of the "Theme and delay" section reproduces the same issue.
But that issue caused by `delayHide`.

Please, provide more information how to reproduce this.

**Comment by ryanhca** [comment]
to clarify @philraj and along with what @ajritch said, I'm not using this as a top level element at all. It's actually being used on a table that lazy loads rows "Fixed-Data-Table" to be exact. I ended up re writing the table and building my own tooltip. haha good ol' fashioned work around/work through. 

@huumanoid to reproduce, simply install the element, hover to activate and show the tooltip, and start scrolling. It wont go away. :)

**Comment by philraj** [comment]
@huumanoid No, can't reproduce it with the examples given. It might be because I'm using the tooltips within `overflow: scroll` containers in my project. Are you able to test that case? I don't have time to test it myself unfortunately.

I am using a single `<ReactTooltip/>` component but that doesn't seem to be the deciding factor here.

**Comment by huumanoid** [comment]
Thanks guys. I think I've catched it. I'm going to fix it in 3.2.11 or 3.2.12.

```jsx
<div id="root">
  <ReactTooltip />
  <div style={{ width: '500px'; height: '500px' }} />
</div>
```

**Comment by guzhavin** [comment]
This problem solved?

**Comment by ryanhca** [comment]
I believe so. Should I close the issue?

**Comment by guzhavin** [comment]
@ryanhca I see this bug in the current version.

**Comment by thomashibbard** [comment]
@aronhelser  As of `3.6.0`, this is still not working for me by adding the attributes `data-scroll-hide` on the tooltip and `scrollHide` on the `ReactTooltip` component. Unless the intention is that it waits until scrolling is stopped before the tooltip is removed.

**Comment by aronhelser** [comment]
I'm not sure I understand, but it could be. What behavior do you expect if you set both delayHide and scrollHide? Based on the behavior of the tooltip in the "Theme and Delay" section of the demo (http://wwayne.com/react-tooltip/) I think the tooltip hanging around for the delay after a scroll is the expected behavior.

**Comment by thomashibbard** [comment]
@aronhelser I wouldn't think so. If a user scrolls down the page for several seconds (slowly, or it's a large page) the tooltip will remain positioned in its static position on the page for the entire time. It's really odd looking (ie, looks buggy) to just have it hanging out there for the entire duration of the scroll. For me it should disappear after scroll-start + delay, or have its own delay entirely.

**Comment by aronhelser** [comment]
Can you file a new issue?

**Comment by essaji** [comment]
I am still facing this issue in `3.6.1`

**Comment by yarik-vv** [comment]
We are still see this issue in `v3.9.2`.

**Comment by umihui** [comment]
I am still see this issue in `v3.10.0` if I set `delayHide`
> Ah, I see it is only failing to work when you set a delayHide. Is this a bug?

**Comment by kashifshamaz21** [comment]
I think this issue arising due to combination of _delayHide_ and _scroll_ is being tracked under #474, for others who stumble here on this issue for this, lets use Issue 474 for adding comments, up-voting and further analysis/PR.

**Comment by filipkowal** [comment]
> Based on a comment in #291, there is a work-around. add `data-iscapture="true" ` to your tooltip target. I'm not sure what other implications this has, though.

If the event target is an SVG, the tooltip will appear only on hovering over the strokes.
Can easily be fixed:
```
  svg {
    pointer-events: all;
  }
 ```

**Comment by emre-ozgun** [comment]
I'm experiencing this issue on desktop as well. v4.2.21 - super vexing since I rely heavily on z-index manipulation so not being able to hide on scroll would hinder our users' experience.
