### ISSUE TITLE
data-event with both 'click' and 'hover'

### ISSUE THREAD

**Issue by matheusml** [wwayne/react-tooltip#249]
After reading the docs, I've realized that if you want to trigger with a hover, you can simply remove the ```data-event``` option, like this:

```javascript
<a data-tip=""><img src={alertIcon} alt="Alert icon" /></a>
```

And, if I want to trigger with a click option, I can put the ```data-event``` option with a click:

```javascript
<a data-tip="" data-event="click"><img src={alertIcon} alt="Alert icon" /></a>
```

But I need is both triggering with a hover or a click. I try this:

```javascript
<a data-tip="" data-event="click hover"><img src={alertIcon} alt="Alert icon" /></a>
```

and also this:

```javascript
<a data-tip="" data-event="click mouseenter"><img src={alertIcon} alt="Alert icon" /></a>
```

but it didn't work. Is there a way for me to do this?

**Comment by matheusml** [comment]
this worked:

```javascript
<a data-tip="" data-event="mouseenter click">
```

**Comment by wwayne** [comment]
@matheusml Really? I just did some test and was writing a comment for you.
In this way, the tooltip won't have `float` effect, it doesn't matter if you just want a `solid` effect tooltip.
