### ISSUE TITLE
Does not show tooltip on dynamic components

### ISSUE THREAD

**Issue by jeanmichelcote** [wwayne/react-tooltip#250]
Consider this basic multi language switch (toggle) component:

```
import { injectIntl } from 'react-intl';
import messages from './messages';

function Switch({isOn, intl}) {
  const {formatMessage} = intl;

  const dataAttrs = {
    'data-tip': '',
    'data-for': 'dynamic'
  };

  const tooltipProps = {
    'place': 'right',
    'effect': 'solid'
  };

  const ToggleSwitch = bool => bool ? <ToggleOnIcon {...dataAttrs} /> : <ToggleOffIcon {...dataAttrs} />;

  return (
    <ReactTooltip
      id="dynamic"
      getContent={() => isOn ? formatMessage(messages.on) : formatMessage(messages.off)}
      {...tooltipProps}
    />

    {ToggleSwitch(isOn)}
  )
};

export default injectIntl(Switch);
```
It does render the tooltip the first time around, whatever `isOn` value may be. But as soon as I click the button, the icon changes, a new component is rendered and the tooltip just disappears not to be seen again.

It means that, at the moment, the react-tooltip package is incompatible with i18n or any dynamically rendered component. Unless I am wrong, which is absolutely possible. Just please let me know where I messed up.

**Comment by jeanmichelcote** [comment]
Closing this issue, I fiddle around and discovered it had to do more with https://github.com/wwayne/react-tooltip/issues/231

**Comment by amoghkapoor** [comment]
> Closing this issue, I fiddle around and discovered it had to do more with #231

Hey, how did you proceed further, because I am not able to get a tooltip over a dynamic react component
