### ISSUE TITLE
Access to SHOW class

### ISSUE THREAD

**Issue by alexeymolchan** [wwayne/react-tooltip#263]
Hi, can you please provide access to class that added when tooltip is displayed ?

For example i need opacity: 1 when tooltip is showed.

**Comment by huumanoid** [comment]
Well, I suppose that `show` class, added when tooltip is displayed, may be considered as stable.
So why don't you use `.myCustomTooltipClass.show` selector instead?

**Comment by alexeymolchan** [comment]
Because i'm using JSS, and can't get this class like you write above :(
