### ISSUE TITLE
Only one tooltip open at time.

### ISSUE THREAD

**Issue by ferpintado** [wwayne/react-tooltip#265]
I have a list of elements which each one has an anchor that launches the tooltip on click event.

Is there any way to have only one tooltip shown at any given time?

Thanks

**Comment by huumanoid** [comment]
I think the easiest way to achieve so is to have only one `<ReactTooltip />` component corresponds to the whole list of elements. Tell me, what you think about it.

**Comment by ferpintado** [comment]
That might work! Thanks

**Comment by huumanoid** [comment]
Hey @ferpintado I'm assuming that this issue is fixed for you.
Please, let me know if I'm wrong.

**Comment by Los83** [comment]
Is there another way to do this with multiple <ReactTooltip /> instances ?

**Comment by Los83** [comment]
@huumanoid  is there another way to do this with multiple ```<ReactTooltip />``` instances?

**Comment by camiblanch** [comment]
This doesn't seem to work for me. I think it might be because I am showing the tooltips using `ReactTooltip.show()`.

**Comment by camiblanch** [comment]
I was able to get it to work after adding `data-for` to the inputs I have the tooltips bound to and adding `id` to the ReactTooltip components that correspond with them. Hope that helps anyone else having the same problem as me!

**Comment by aronhelser** [comment]
Great - glad to hear you got it working.

**Comment by khalid3n** [comment]
I am trying to get my head around it. I have a form which has multiple fields and I have to show tooltips onClick for each one, but If I click one tooltip to show, and then click on another the previous one doesn't close. Is there any way to show only one tooltip at the same time?

here is my code. I have written a wrapper component
`class Tooltip extends React.PureComponent {
  render() {
    const {
      text,
      children,
      position,
      event,
      effect,
      className,
      id,
    } = this.props;
    return [
      <a
        data-tip
        data-for={id}
        data-event={event}
        data-place={position}
        data-multiline
        data-effect={effect}
        data-html
        className={className}
        // data-event-off="click"
      >
        {children}
      </a>,
      <ReactTooltip
        globalEventOff="click"
        // eventOff="click"
        multiline
        html
        id={id}
        className="tooltip--bubble"
      >
        {text}
      </ReactTooltip>,
    ];
  }
}`

**Comment by aronhelser** [comment]
Yes, instead of including the `ReactToolTip` in this component, you keep it separate. There will be a single `id`, but each `<a>` should set `data-tip={text}`
HTH

**Comment by anatel** [comment]
@aronhelser Would the solution you suggested to @khalid3n work if I use `getContent`?
then I can't use `data-tip` or `data-html` since I need to have a react component as the content.

**Comment by aronhelser** [comment]
I don't know....

**Comment by mongsukim** [comment]
Hello everyone, 
could you please show the code to solve this problem 
**as a functional component?**

please help me
