### ISSUE TITLE
When changing the data-tip doesn't refresh the the tooltip

### ISSUE THREAD

**Issue by ctaloc** [wwayne/react-tooltip#27]
I have this tooltip, that has a dynamic data-tip:
    
    <span data-tip={switchTip} onClick={this.props.switchType}><i className="icon-refresh" />Switch to {oppositeType}</span>

when switchTip changes, it doesn't refresh the information inside the data-tip, is this an issue, or more like a feature?

Thanks in advance!

**Comment by wwayne** [comment]
I've checked this and it's works well for me, so I guess:
1. Maybe your click event `onClick={this.props.switchType}` doesn't work
2. You can try to put `<ReactTooltip />` in the last(outmost) level , for example:
```
return(
 <section>
   ... // your components
   <ReactTooltip />
 </section>
)
```

this is part of my test code

```
constructor() {
 this.state = {
  text = "text1"
 }
}

_onclick() {
 this.setState({
  text: text2
 })
}
<span data-tip={this.state.text}></span>
<button onClick={this._click.bind(this)}>Click</button>
```

**Comment by ctaloc** [comment]
Thanks @wwayne, I'm gonna try that out :)

**Comment by ctaloc** [comment]
I mean, the text wont refresh until I do trigger again 'mouseleave' and 'mouseenter', is there a way that the component runs again showTooltip(e) if that happens?, sorry, I'm new to the Reactjs world :)

**Comment by wwayne** [comment]
Ok I get you. Currently, for this tooltip component, the answer is no.
`showTooltip` only triggered by `mouseenter` and this component doesn't provide any way to add some event listener to trigger `showTooltip`

**Comment by ctaloc** [comment]
Ok, got it, thanks anyway!

**Comment by alejandrosobko** [comment]
You have to add **getContent** to the ReactTooltip.
This worked for me:
```
<span data-tip={this.copyMessage()} />
<ReactTooltip effect="solid" getContent={this.copyMessage} />
```

copyMessage is the function that returns the message dynamically.

**Comment by Yarflam** [comment]
> ```
> <span data-tip={this.copyMessage()} />
> <ReactTooltip effect="solid" getContent={this.copyMessage} />
> ```

I don't understand, where you write your text? What is the function copyMessage()?
