### ISSUE TITLE
Doesn't work on disabled inputs

### ISSUE THREAD

**Issue by Wayneio** [wwayne/react-tooltip#276]
If an input is disabled, the tooltip doesn't show.

**Comment by huumanoid** [comment]
It seems like disabled `<input>` doesn't emit any pointer events.

Try to wrap your input in another element, like span!

http://hmnid.ru:8090/disabled-input

https://github.com/huumanoid/react-tooltip-issue-test/blob/master/src/disabled-input.jsx

**Comment by huumanoid** [comment]
Hey @Wayneio I'm considering this issue as resolved. If I'm wrong, please, let me know!
