### ISSUE TITLE
Add Multiline tooptip

### ISSUE THREAD

**Issue by milon521** [wwayne/react-tooltip#28]
Please add multiline tooltip options.

**Comment by pvsrivathsa** [comment]
Would be very useful.

**Comment by wwayne** [comment]
`data-tip="text text2"` `data-tip="text<br />text2` `data-tip="text<br>text2"`
In the latest release(0.3.7), all these formats can generate multi-line tooltip

**Comment by milon521** [comment]
Thanks. great job @wwayne
