### ISSUE TITLE
Class on trigger when active

### ISSUE THREAD

**Issue by kennykaye** [wwayne/react-tooltip#290]
Currently there doesn't seem to be a way to determine if a given trigger has an active tooltip. Would it be possible to add some class (perhaps `active`) to indicate when the tooltip is being shown?

**Comment by AyWa** [comment]
Hey @kennykaye 

There is the class "show" when the react tooltip is being shown.
So I guess with something like
```
<p data-tip='' data-for='test'></p>
<ReactTooltip id='test'></ReactTooltip>
```
You can check if for the <p> the reactTooltip with is shown or not. (target the id and then the active class ?)
Maybe I missunderstand your question.

**Comment by kennykaye** [comment]
Ah, I'll clarify.  For the following example, it would be useful to know, in the context of the `data-tip` element, in this case `h4`, when the `ReactTooltip` is being shown.

```javascript
<h4 data-tip data-for="actions" data-event="click">Actions</h4>
<ReactTooltip id="actions" globalEventOff="click" >{ /* content */ }</ReactTooltip>

```

**Comment by AyWa** [comment]
Yeah It could be usefull I am agree. 

however you can achieve what you want to do: 
```
<h4 data-tip data-for="actions" data-event="click">Actions</h4>
<ReactTooltip ref="myRef" id="actions" globalEventOff="click" >{ /* content */ }</ReactTooltip>
```

and somewhere in your logic:
`this.refs.myRef.state.show`

**Comment by kennykaye** [comment]
@AyWa Your suggestion does satisfy the requirement 👍. This issue could be closed unless you want to keep it as a feature request.
