### ISSUE TITLE
data-tip only support string?

### ISSUE THREAD

**Issue by duckscofield** [wwayne/react-tooltip#298]
I have structure layout issue, so I use **'data-tip'** to pass content into `<ReactTooltip  />`, like `<img />`, but it will show **[object object]**. If I put `data-tip="<div>test</div>"`, it will get the same result [object object]. Is it possible to add the feature?

**Comment by ioan-ungurean** [comment]
Is this what you are looking for? That's already implemented. Check the spec.
![image](https://cloud.githubusercontent.com/assets/25197517/26356079/93692280-3fd3-11e7-9b13-81ad12c9861d.png)

**Comment by duckscofield** [comment]
cool! It works, thank your

**Comment by paulcredmond** [comment]
@duckscofield How did you get this to work? I'm having the same problem. I tried the `html={true}` as posted above but I get the same result.

**Comment by duckscofield** [comment]
@paulcredmond 
In my case, I use the code like as bellows:

<YourComponentName
...
data-for="one id name"
data-html
data-tip={
  `<img src="" alt=""/>`
}
...
/>

**Comment by paulcredmond** [comment]
Thanks for the reply @duckscofield 

Mine is a little more complicated as I have unparsed tags, but I figured it out using the following:

```
 const unParsedHtml = "&lt;p&gt;Thank you for your message&lt;/p&gt;";
 const htmlDecode = (input) => {
      const e = document.createElement('div');
      e.innerHTML = input;
      return e.childNodes.length === 0 ? "" : e.childNodes[0].nodeValue;
 }

<ReactTooltip class="react-tooltips" place="right" effect="solid">
    <div dangerouslySetInnerHTML={{ __html: htmlDecode(unParsedHtml) }} />
</ReactTooltip>
```

**Comment by pjisha** [comment]
It doesn't work for me either. Displays [object Object]. Tried setting data-html to true. But still no luck.

**Comment by pjisha** [comment]
Found this thread - https://github.com/wwayne/react-tooltip/issues/329. The data-tip doesn't support jsx.
