### ISSUE TITLE
Rebuild event listeners when needed

### ISSUE THREAD

**Issue by EragonJ** [wwayne/react-tooltip#30]
Hi @wwayne, do you think it is reasonable to let React-Tooltip register a customized event to make sure it can rebuild listeners when needed ? 

Right now, ReactToolip only works for pre-existed elements and if the DOM structure is changed, new-added elements will not be handled by this component.

Any idea ?

**Comment by wwayne** [comment]
@EragonJ  Good point, thanks.
I don't know if registering a custom event is the best way but it sounds good to me, let me try on it when I have time and welcome PR and advice.

**Comment by EragonJ** [comment]
I added this for my personal use : https://github.com/EragonJ/react-tooltip/commit/599145bbe82b0ac24aa40016b86c27b5c3a0d2db

If you are fine with this implementation for better idea, I am willing to help.

**Comment by EragonJ** [comment]
The main problem is that it's hard to manipulate ReactTooltip from outside of the world (Or is it possible to expose any method for outer use ?) 

Some idea from the document : https://facebook.github.io/react/tips/communicate-between-components.html

> For communication between two components that don't have a parent-child relationship, you can set up your own global event system. Subscribe to events in componentDidMount(), unsubscribe in componentWillUnmount(), and call setState() when you receive an event. Flux pattern is one of the possible ways to arrange this.

**Comment by EragonJ** [comment]
or, we can add one extra property for ReactTooltip to let users to decide whether they want to register this global event or not ?

**Comment by wwayne** [comment]
@EragonJ  really appreciate for your enlightenment
now users can use `ReactTooltip.hide()` or `ReactTooltip.rebuild()` to dispatch global event

```
import ReactTooltip from 'react-tooltip'

class MyComponent extends React.Component {

onClick() {
  // will dispatch a global event, do unbind then bind 
  ReactTooltip.rebuild()
}

render() {
  <div>
   <a onClick={::this.onClick}>rebuild</a>
   <ReactTooltip />
  </div>

}

}
```

**Comment by EragonJ** [comment]
@wwayne +++ !! Glad to see this patch :P
