### ISSUE TITLE
Usage with react-virtualized

### ISSUE THREAD

**Issue by sedouard** [wwayne/react-tooltip#300]
Has anyone had any luck getting the position correct using a `react-tooltip` within a `react-virtualized` list?

It seems like the `react-tooltip`'s can't get their position right and they get confused about their position within the virtualized list.

**Comment by sedouard** [comment]
Turns putting `react-tooltip`'s within a `react-virtualized` `List` is really complicated. Best to bind `react-tooltip`'s from outside of virtualized components.

**Comment by Typhon66** [comment]
@sedouard What did you end up doing to fix this?

**Comment by sedouard** [comment]
You have to place the tooltips outside of the virtualized area and have them be not virtualized. The way absolute positioning works within the virtualized area is pretty tough because you need to know how many items are rendered above an arbitrary point in the virtualized list.

So we build the tooltips first:

```js
const tooltips = projects.map(({ id }) => <ReactTooltip id={id} key={id} effect="solid" />);
```

And then place them outside of the virtualized list:

```js
render () {
  <List
    onScroll={
                      throttle(() => {
                        ReactTooltip.rebuild();
                        ReactTooltip.hide();
                      }, 200)
                    }>
  </List>
  // render tooltips for current virtualized list
  {tooltips}
}
```

When we load more rows we'll re-render the the component which adds and rebuilds the tooltips for the newly scrolled area. We end up having more tooltips than we need as the user scrolls but it isn't that big of a deal for us.

**Comment by AO17** [comment]
@sedouard  I'm having the same issue, in my case it's `Autosizer` and `Table`. Do you have another example or a more simple example/ approach to this?

**Comment by codygordon** [comment]
For anyone still looking for a solution with `AutoSizer` + `Table`, I got this working performatively.

I found that rendering a `Tooltip` for each row as recommended had a dramatic effect on performance with more than a small number of rows, so I wanted to get it working by only rendering one. The important part is just calling the tooltip methods (note I used a trailing `debounce` instead of `throttle` just to make sure that the method is always called at the end of every burst of scroll events).

See a working example: https://codesandbox.io/s/r5393l62pm

**Comment by aronhelser** [comment]
That's a really nice simple example - thanks! I think it'd be good to add a link in the Readme or in the examples page - anyone want to do a PR?

**Comment by angel-langdon** [comment]
> You have to place the tooltips outside of the virtualized area and have them be not virtualized. The way absolute positioning works within the virtualized area is pretty tough because you need to know how many items are rendered above an arbitrary point in the virtualized list.
> 
> So we build the tooltips first:
> 
> ```js
> const tooltips = projects.map(({ id }) => <ReactTooltip id={id} key={id} effect="solid" />);
> ```
> 
> And then place them outside of the virtualized list:
> 
> ```js
> render () {
>   <List
>     onScroll={
>         _.throttle(() => {
>         ReactTooltip.rebuild();
>         ReactTooltip.hide();
>         }, 200)
>     }>
>   </List>
>   {tooltips}
> }
> ```
the onScroll part is really important, otherwise it is not going to work

**Comment by angel-langdon** [comment]
I ended up using `Material UI` tooltip, it works out of the box https://mui.com/components/tooltips/

**Comment by aronhelser** [comment]
@angel-langdon How do you think the material UI tooltip and this project compare? Are there missing features? Would you recommended it generally, or only in specific cases?

Since this project is not actively developed, it might be nice to gather some recommendations like this...

**Comment by angel-langdon** [comment]
@aronhelser I am not an expert in `react-tooltip` nor `Material UI` but `Material UI` tooltip works out of the box even in the `react-virtualized` context, no need for weird code (technical debt) in `onScroll` event handler.

**Comment by aanbari1337** [comment]
> > You have to place the tooltips outside of the virtualized area and have them be not virtualized. The way absolute positioning works within the virtualized area is pretty tough because you need to know how many items are rendered above an arbitrary point in the virtualized list.
> > So we build the tooltips first:
> > ```js
> > const tooltips = projects.map(({ id }) => <ReactTooltip id={id} key={id} effect="solid" />);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then place them outside of the virtualized list:
> > ```js
> > render () {
> >   <List
> >     onScroll={
> >         _.throttle(() => {
> >         ReactTooltip.rebuild();
> >         ReactTooltip.hide();
> >         }, 200)
> >     }>
> >   </List>
> >   {tooltips}
> > }
> > ```
> 
> ### the onScroll part is really important, otherwise it is not going to work

and if  have a list of 500 projects it's not good to render 500 <Tooltip />

**Comment by danielbarion** [comment]
Hi @aanbari1337, this issue is related to v4.

Can you please take a look at V5 docs?

https://react-tooltip.com/docs/examples/multiple-anchors

In this doc, you can have one tooltip for 500 anchor elements.
