### ISSUE TITLE
Support SVG elements?

### ISSUE THREAD

**Issue by tanykim** [wwayne/react-tooltip#306]
I tried to add this tooltip on SVG elements but seems like it doesn't support SVG. I thought it was z-index issue, but even though I manually set z-index and css position properties, but I had no luck.

Any solutions for this?

**Comment by redwarff** [comment]
Hi, I have just bumped into the same issue, but for me it actually works like it should. Just make sure to mount the <ReactTooltip /> component outside of <svg> and add the `data-tip` attribute directly onto svg elements (e.g. <line data-tip="..." />).

**Comment by rayjsiu** [comment]
Thanks @redwarff, that helped me as well!

**Comment by pelotom** [comment]
@redwarff I'm doing this, it doesn't seem to work at all 🤷‍♂️

**Comment by ryandorward** [comment]
Is there an equivalent technique for v5 ? it looks like `Tooltip.rebuild` is not a function in v5

Thanks for the great project.

**Comment by gabrieljablonski** [comment]
> Is there an equivalent technique for v5 ? it looks like `Tooltip.rebuild` is not a function in v5
> 
> Thanks for the great project.

Do you mind opening a new issue with sample code or a CodeSandBox demonstrating the problem on v5? As I see it, v5 should work fine with svg elements without any extra work, but we'll see what we can do if it's not the case.

**Comment by ryandorward** [comment]
Thank you. I will make sure I'm not doing something wrong before creating the issue. 
I'm using `react-tooltip` to create tooltips on markers for Mapbox maps. I used following technique in v4 to get the tips to show up:

```
const mounted = useRef();
useEffect(() => { // update the ReactTooltips as elements in the svg/map change
	mounted.current ? ReactTooltip.rebuild() : mounted.current = true
})
```

In v5 I tried without that technique and the tips didn't show up, but it's possible I'm doing it wrong.

**Comment by gabrieljablonski** [comment]
> In v5 I tried without that technique and the tips didn't show up, but it's possible I'm doing it wrong.

Try following the examples in the docs and getting the tooltip to work on regular html elements, then try it on svgs. If it doesn't work on svgs, please open an issue with some sample code. Thanks.

**Comment by ryandorward** [comment]
I can confirm that `react-tooltip` v5 is working properly in conjunction with map markers using `react-map-gl`, I was just doing it wrong previously. Thanks!
