### ISSUE TITLE
Tooltip double-compensates for scroll-position

### ISSUE THREAD

**Issue by Venryx** [wwayne/react-tooltip#308]
Tooltips which are inside a scroll container, seem to be placed with an attempted-matching scroll-offset, however it ends up double-compensating! That is, when I scroll down by 100px, the tooltip moves up on-screen by 200px!

Here's a gif demonstrating the issue:
http://i.imgur.com/XnuYycj.gifv

And here is the JSX code:
```
<ReactTooltip id="tip1" effect="Float">
	<Pre>"Hi there:</Pre>
</ReactTooltip>
```

**Comment by Venryx** [comment]
Okay, found the cause. I had `style={{willChange: "transform"}}` on the container inside the scroll-view.

The willChange property causes "position: fixed" to be relative to that element (well, that's one of the side-effects).

**Comment by sarnielmorgia** [comment]
Had the same issue before and manage to fixed it. It is something to do with the css transform. Make sure to put transform: none; to your main container and voila!! your welcome.
