### ISSUE TITLE
Tooltip does not fade out when hovered element is removed

### ISSUE THREAD

**Issue by andrewluetgers** [wwayne/react-tooltip#31]
Scenario, I have a delete button on a thing, button has a tooltip.
I hover the button, tooltip shows.
I click the button, button goes away, tooltip remains

**Comment by bradcerasani** [comment]
+1, would also appreciate a fix for this

**Comment by wwayne** [comment]
Now in 0.6.0, users can use `ReactTooltip.hide()` to dispatch a global event to hide tooltip

```
import ReactTooltip from 'react-tooltip'

class MyComponent extends React.Component {

constructor ()  {
  super()
  this.state = {
    showButton: true
  }
}
onClick() {
  this.setState({
     showButton: false
  })
  ReactTooltip.hide()          // this will dispatch a global event to hide current tooltip
}

render() {
  <div>
    {this.state.showButton &&
       <a data-tip="tooltip" onClick={::this.onClick}>Button</a>
    }
   <ReactTooltip />
  </div>

}

}
```

In this situation, you have to manually hide the tooltip so that you can control tooltip in any situation even in Redux, Flux.
