### ISSUE TITLE
It's  possible to Using react component as tooltip content and for global tooltip layer?

### ISSUE THREAD

**Issue by ccjoe** [wwayne/react-tooltip#327]
as title description, thx
try component as content , it's just show [object Object]

**Comment by danieleleoni** [comment]
I have the same question...

**Comment by danieleleoni** [comment]
I think the correct way to display a component is to use something like example:
```
<a data-tip data-for='happyFace'> d(`･∀･)b </a>
<ReactTooltip id='happyFace' type='error'>
  <span>Show happy face</span>
</ReactTooltip>
```

**Comment by ccjoe** [comment]
yes, ur right, but I need to update the content `<span>Show happy face</span>` with other react component, 
because i used global ReactTooltip

**Comment by ccjoe** [comment]
It's supported, I add html={true}, so it's not work well
