### ISSUE TITLE
Color on the top tooltip arrow

### ISSUE THREAD

**Issue by amymarco** [wwayne/react-tooltip#333]
Hi!

I'm trying to customize my border color for my tooltip. It works for the primary border shape, but leaves the arrow a black color. Is there a way to also customize that color so the whole thing is consistent?

How it currently looks:
<img width="104" alt="screen shot 2017-09-07 at 11 43 36 am" src="https://user-images.githubusercontent.com/1859475/30179860-c5482132-93c2-11e7-9164-46c77d981650.png">

My current code:

css
```
  .tooltip-custom {
    font-weight: bold;
    border-radius: 2rem;
    border: 1px solid $color !important;
    color: $color !important;
  }
```

```
<ReactTooltip id='icon' place='bottom' class='tooltip-custom' type='light' border='true'/>
```

Thank you!

**Comment by ali-sadeghin** [comment]
Hi @amymarco 
Did you find your way around this issue? 
I'm facing the very same problem and can't figure out how to change the black color of the arrow. 
Thanks

**Comment by amymarco** [comment]
this seemed to do the trick:

```
.__react_component_tooltip.type-light.border.place-bottom:before{
            border-bottom:8px solid $adorapink;
    }

    .tooltip-custom {
      font-weight: bold;
      border-radius: 2rem;
      border: 1px solid $your_color !important;
      color: $your_color !important;
```

**Comment by ali-sadeghin** [comment]
Thanks a bunch @amymarco , you saved my life ;-)

**Comment by vonubisch** [comment]
If you don't want to use a custom class:

    .__react_component_tooltip.place-left::after {
        border-left: 8px solid red !important;
    }

    .__react_component_tooltip.place-right::after {
        border-right: 8px solid red !important;
    }

    .__react_component_tooltip.place-top::after {
        border-top: 8px solid red !important;
    }

    .__react_component_tooltip.place-bottom::after {
        border-bottom: 8px solid red !important;
    }

**Comment by HappyArava** [comment]
You saved me Man, Thank You...!!!
