### ISSUE TITLE
Link not clickable in tooltip 

### ISSUE THREAD

**Issue by dankonino** [wwayne/react-tooltip#336]
Hey guys, in the screenshot you can see my React tooltip being used. I managed everything nicely.
But if I pass this inside the tooltip, you can see it there. It's not clickable. Yeah w3 that desperate I was -> I passed normal 
        ```<div className={css.link}>
                <a href="https://www.w3schools.com">Visit W3Schools</a>
            </div>```
Can it be that it's not supported or rather my css imports could be breaking that?  TY :) 

<img width="421" alt="screen shot 2017-09-13 at 12 25 07 am" src="https://user-images.githubusercontent.com/8626427/30514449-a4dc1800-9ae2-11e7-9b6c-49a56b376de7.png">

**Comment by phuochau** [comment]
@dankonino did you solve this issue? I'm trying to fix it too

**Comment by dankonino** [comment]
Nah we just made decision that link will be displayed somewhere else. Didn’t hack it at all

**Comment by phuochau** [comment]
@dankonino just fixed by css

`
.__react_component_tooltip {
  pointer-events: auto !important;
}`

**Comment by dankonino** [comment]
@phuochau wow man thanks will do it also ! :)
