### ISSUE TITLE
unnecessary orientation correctors

### ISSUE THREAD

**Issue by tatsujb** [wwayne/react-tooltip#338]
first off : amazing work! this is so simple to use and clean.

I have my tooltip info icon on the rightmost border of the screen and I chose to display towards the top but it defaults to left : is this intended behavior? if so could we have a parameter to disable this behavior. I don't really care if the pointing arrow breaks or disappears. choosing what I overlay is a bigger priority.

thanks

**Comment by aronhelser** [comment]
I believe your content is big enough that displaying a centered tooltip to the top will cause it to run off the right edge - thus the correction to display it to the left. I don't think you'd want your content to get cut off - what solution do you suggest? 

You can play with resizing the examples page to see how it behaves when hitting the edges...

**Comment by Rogger794** [comment]
place="top" effect="solid" should be work. I will close this issue.
