### ISSUE TITLE
Tooltip inside a Button is not working only in Firefox

### ISSUE THREAD

**Issue by ibrahimilu** [wwayne/react-tooltip#339]
<button type={"button"} >
          <i data-tip={"tooltip here"} data-for="widget-tooltip" className={"fa fa-info"}></i>
          <ReactTooltip id='widget-tooltip' />
</button>

**Comment by benmccormick** [comment]
This is a browser level bug and a dup of https://github.com/wwayne/react-tooltip/issues/296
