### ISSUE TITLE
CSP

### ISSUE THREAD

**Issue by markusv** [wwayne/react-tooltip#340]
Hi,

it seems that this library uses inline styles to add its styling. This is a problem for the recommended CSP style rule:

style-src 'self'

I would be happy to include the css in my project, and this problem would be fixed..

Regards,
Markus

**Comment by aronhelser** [comment]
what is CSP?

**Comment by markusv** [comment]
CSP stands for Content Security Policy

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by aronhelser** [comment]
Does this commit:
https://github.com/wwayne/react-tooltip/commit/82e3f885ee3a06a11b0694fb4ea4de269e038a41
address your concern? It looks like you can set 'insecure=false' as a
property and avoid style injection. Or am I misunderstanding the issue?

**Comment by myfoxtail** [comment]
@markusv it is solved in the new versions (3.6.0 works well).

**Comment by myfoxtail** [comment]
@aronhelser the thing is that your styles are being embedded on the page by one of your js files and it does not work with strict content security policy unless you put the hash.

So the question is can you move all your styles to a separate css file?

**Comment by aronhelser** [comment]
@myfoxtail could you try out the `insecure=false` option and tell me if that fixes the issue? I'm not sure if the styles are still included, but just not injected?

**Comment by myfoxtail** [comment]
Hi @aronhelser 

Thank you for the response. `insecure=false` option removes styles from the header tag which is cool, but I cannot find any css file I can add to my bundle.

I'm afraid that the package you deliver with npm does not contain any css files (please refer to image below):

![image](https://user-images.githubusercontent.com/4619214/40336248-e8373e36-5dab-11e8-944c-8d12b11b7e4a.png)

Though I can see that it's in the source code.

**Comment by plondon** [comment]
https://github.com/wwayne/react-tooltip/pull/412

**Comment by Fandekasp** [comment]
@aronhelser is the insecure prop still needed now that https://github.com/wwayne/react-tooltip/commit/ce365fe5af23254b074712027e7c4fb7b4c2685f was merged ?

**Comment by jorrit** [comment]
Personally, I would prefer to include the CSS file myself. It would be great if the CSS file would be added to the NPM package. On my site, the dynamic CSS file is sometimes inserted a little too late, displaying the popup text.

**Comment by Rogger794** [comment]
Already change the style imported.

**Comment by fabiolmorato** [comment]
If anyone has issues with this and cannot enable the `style-src 'unsafe-inline'` CSP rule, do this:

```jsx
import { Tooltip } from "react-tooltip";

import "react-tooltip/dist/react-tooltip.css";

export function Test () {
  return (
    <Tooltip
      // ...
      disableStyleInjection="core"
    />
  );
}
```

**Comment by z-akashGupta** [comment]
@fabiolmorato How to do it they have react-tooltip@3.11.1 and cannot update this. As old version does not have css file in it

**Comment by danielbarion** [comment]
@z-akashGupta this solutions is for >= v5, I strongly recommend you to update it.
