### ISSUE TITLE
Tooltip redering twice in two seperate positions

### ISSUE THREAD

**Issue by tatsujb** [wwayne/react-tooltip#346]
![image](https://user-images.githubusercontent.com/5132359/31333402-3b50d8a2-acea-11e7-80ff-9ca5cf10102b.png)

```
<div
                                                className="btn-greyed-out"
                                                data-tip={"Veuillez S'il vous plaît d'abords fournir des modifications au template "+ currentTemplate + "."}
                                            >
                                                <div><i className="fa fa-floppy-o" /> Sauvegarder en Template</div>
                                            </div>
                                            <ReactTooltip place="top" type="info" effect="solid" />
```

why is it doing this?

If I place it left or right it shows on the left in both of those case and not on top (also you'll notice the one on the left is darker making me think there's 2 or more showing on the left.

**Comment by Sedaj** [comment]
Check if you don't create <ReactTooltip /> within a loop, but outside

**Comment by canoqb10** [comment]
you must write "data-for" in your component and will reference <ReacTooltip> with "id" to "data-for".
for example:
<a data-tip data-for='global'> ....something ....</a>

<ReactTooltip id='global'......./>

**Comment by urirahimi** [comment]
I'm getting this issue but I implemented data-for with a match the tooltip id

**Comment by cheriejw** [comment]
I had this issue with `data-for` and `id` as well, the solution for me was to set a more unique identifier/a combination of a word and a variable that I was getting from the parent component (i.e. ``` id=`tooltip-${parent.id}` ```).
