### ISSUE TITLE
No "construct or call signatures"

### ISSUE THREAD

**Issue by jccrofty30** [wwayne/react-tooltip#352]
```
yarn add react-tooltip
yarn add --dev @types/react-tooltip
```

```jsx
import * as ReactTooltip from 'react-tooltip';
...
<ReactTooltip {...props}>foo</ReactTooltip>
```

Receive error:
```
[at-loader] <path>/index.tsx:647:46
    TS2604: JSX element type 'ReactTooltip' does not have any construct or call signatures.
```

**Comment by FlorianWendelborn** [comment]
@aronhelser I can confirm that your suggested fix fixes this issue. I think this ticket can therefore be closed.

Appeared for me when migrating from `create-react-app-typescript` to `create-react-app`.

**Comment by aronhelser** [comment]
Thanks for confirming!

**Comment by comorina** [comment]
![image](https://user-images.githubusercontent.com/78028738/229492441-7ed91d14-9740-475c-9f1d-9e9790d4edbf.png)

"I am getting an error: 'JSX element type 'ReactTooltip' does not have any construct or call signatures'. I tried to fix it, but I didn't understand why this error occurred."

I hope this helps! Let me know if you have any further questions.

**Comment by gabrieljablonski** [comment]
@comorina Please have a look at the [V5 docs](https://react-tooltip.com/docs/getting-started). 

Make sure to read the "Getting started" section thoroughly, and if you run into any problems, feel free to open a new issue with more details.
