### ISSUE TITLE
Anchor position wrong in IE11 when parent container positioned by CSS transform

### ISSUE THREAD

**Issue by Q-Man** [wwayne/react-tooltip#353]
In IE11 the anchor of a Tooltip rendered in a container that has any parent that is positioned by CSS transform is wrong. It acts as if the parent was not moved.

**Comment by teeg82** [comment]
The problem appears to resolve if the `position: fixed` style is changed to `position:absolute`. This style is contained in the `.__react_component_tooltip` class.

**Comment by nikroomancer** [comment]
I can confirm that in IE11 some of the examples on the react tooltip example site do not work. In particular those who have a parent with a css transform.

**Comment by Jarch09** [comment]
FYI - it appears one solution for this is creating the tooltips outside of the modal, and then in the modal's `componentDidMount()` method, you call `tooltip.rebuild()`
