### ISSUE TITLE
Multiline Regex is broken for some languages

### ISSUE THREAD

**Issue by clementoriol** [wwayne/react-tooltip#37]
Hi !
The multiline regex is a bit weird, and breaks easily.
It should detect a line break on `<br>`, `<br/>` and multiple spaces.

Currently, it add breaks on non-word characters, which leads to some unexpected behaviors with special characters and accentued characters from foreign languages.

Could you please consider switching to another regex ?
I'm suggesting `/<br\s*\/?>|\s{2,}/` (untested, but should be fine)

**Comment by wwayne** [comment]
@clementoriol 
Followed your advice, I changed the regex and the only one difference from yours is using `\s{1,}`
Thanks :+1:

**Comment by clementoriol** [comment]
Hey @wwayne , thanks for your reactivity.
However, my understanding is that using `\s{1,}` will make the tooltip add a line-break on **every space** which might not be the desired result.
So something like : 
```Hello testing tooltip```
will output
```Hello\ntesting\ntooltip```

It might be annoying. I would suggest to either limit the regex to searching `<br>`, `<br /> and `<br/>` characters (so : `/<br\s*\/?>/`, and, if you think it's important, to consider that multiple space should be a line-break (by adding the `|\s{2,}` part, which means "a double space or more").

What do you think ?

**Comment by clementoriol** [comment]
Here's a screenshot to where my original regex should break : 
https://www.dropbox.com/s/6pd6ti8xyv71612/Capture%20d%27%C3%A9cran%202015-09-27%2016.57.19.png?dl=0

And yours : 
https://www.dropbox.com/s/p8rqbyq7cnk06zi/Capture%20d%27%C3%A9cran%202015-09-27%2016.57.53.png?dl=0

Is this expected behavior ? :)

**Comment by wwayne** [comment]
@clementoriol 
`\s{1,}` was my expected behavior, but your suggestion made me to re-think about the multiline option.

I think you're right, matching ` \s{1,}` is a bit confused when using multiline, so I think only match `/<br\s*\/?>/` would be a better and more clear choice.

I will change it, and thanks again :)

**Comment by clementoriol** [comment]
Great, I think you're right, it would be a simpler, less confusing choice.

Thanks :)
