### ISSUE TITLE
How to combine getContent() and AJAX request?

### ISSUE THREAD

**Issue by pawelsas** [wwayne/react-tooltip#386]
My data-tip contains a URL. Now I'd like to fetch the data on hover using the URL.
Unfortunately getContent() is fired on render and not on hover.
Is there a way to fire getContent() on hover for the specific item or maybe a different approach to do a ajax request?

My current code:
`<p>Lorem ipsum dolor sit <a href="#" data-for="custom-ttip" data-tip="http://some-url.com">amet</a> consectetur, adipisicing <a href="#" data-for="custom-ttip" data-tip="http://some-other-url.com">elit</a>. Voluptate, reprehenderit.</p>`

```
<ReactTooltip
  id="custom-ttip"
  className="custom-ttip"
  place="top"
  type='light'
  effect='solid'
  getContent={(url) => {
    fetchData(url); // sets state
    return (
      <p>{this.state.fetchedData}</p>
    );
  }}
/>
```

**Comment by aronhelser** [comment]
What about using the 'afterShow' function? I think you will have a delay where the content is not updated yet. You can also add a refresh timer to getContent, if you need to:
```
getContent={[(url) => {
    return (
      <p>{this.state.fetchedData}</p>
    );
  }, 200]}
```

**Comment by pawelsas** [comment]
Thank you for the quick reply.

I already had the same idea. But I can't access the url from 'afterShow'.

**Comment by aronhelser** [comment]
What about caching the results of the fetch with fetchData? so fetchData fills in `this.state.fetchedData[url]`, and you check in getContent? Does the fetched data change?
```
getContent={(url) => {
    if (!this.state.fetchedData[url]) {
      fetchData(url); // sets state
    }
    return (
      <p>{this.state.fetchedData[url]}</p>
    );
  }}
```

I suspect the fetched data changes. If so, you could set a dirty state flag in afterShow, then check in getContent, which means the next getContent would fetch new data.

**Comment by pawelsas** [comment]
Unfortunately the content is completely dynamic. I don't know the urls before the page loads. So depending on the page, there is a dynamic number of a tags with unknown urls (data-tip).
I think I can find a dirty fix but I just wanted to make sure that there's no 'clean' way to do it.

**Comment by aronhelser** [comment]
I don't think there's a better way - getContent is called whenever React decides to render, so it's definitely more often that just when the tooltip is shown. I'll close, reopen if needed....
