### ISSUE TITLE
Add a react component in the tooltip instead of just text

### ISSUE THREAD

**Issue by hackhat** [wwayne/react-tooltip#39]

**Comment by 1vasari** [comment]
:+1: I want to put more than just text in my tooltips. This would be perfect.

**Comment by hackhat** [comment]
This one accepts everything: https://github.com/react-component/tooltip

**Comment by wwayne** [comment]
Support ! 
Example: http://wwayne.github.io/react-tooltip/
HISTORY.MD: https://github.com/wwayne/react-tooltip/blob/master/HISTORY.md

**Comment by nick722** [comment]
Can't see example of using React component into tooltip. Can you please show it explicitly.

**Comment by aronhelser** [comment]
See #378 for an example.
