### ISSUE TITLE
offsets for positioning

### ISSUE THREAD

**Issue by flosse** [wwayne/react-tooltip#4]
With jQuery-UI I was able to define offsets like
`el.tooltip({position: { my: "left+10 center", at: "right center"}})`
Is it possible to do that with your component?

**Comment by wwayne** [comment]
@flosse currently you can't  define position yourself.
Enable define position looks much useful, so I can add this function later or you can give me a pull request( I use npm to run build task ) , thanks for your advice !

**Comment by af7** [comment]
That would be a nice addition, indeed. Thx.

**Comment by wwayne** [comment]
Add position attribute to support this feature ( >= 0.2.7)
