### ISSUE TITLE
Tooltip closing when haven't left the tooltip

### ISSUE THREAD

**Issue by RichMatthews** [wwayne/react-tooltip#403]
I open the tooltip by hovering over an icon. I have then manually changed the styles to be a certain position and width. but the tooltip closes when I leave the hover icon. I want it to any close when I leave only the tooltip area (which is much larger). I want to put a link in the tooltip content and currently the user wont be able to click it because when they get to it, the tooltip has already closed. any ideas? cant see anything in props

FYI: http://wwayne.com/react-tooltip/

the theme and delay section did not work for me. I'm using styled components and applied the visibility and opacity on hover and the tooltip just closed when I left the icon rather than the whole tooltip

**Comment by aronhelser** [comment]
The theme and delay example is the only answer I have to your proposed usage, so I'm not sure why they would work. It seems you may have a CSS issue of some kind which is overriding the intended styles. 

You might try cloning and building react-tooltip, and running the examples, then modifying the example with your style changes to see if you can isolate the problem.

**Comment by chipcullen** [comment]
I was having this issue, and found that they to solving it was the `pointer-events: auto;` in the example that was applied to the popover content. By default, react-popover uses `pointer-events: none;` which will prevent @RichMatthews 's expected behavior.

**Comment by RichMatthews** [comment]
I'm closing this as I found the solution long ago (which was what @chipcullen says above) thanks both
