### ISSUE TITLE
an error occurs when I route to other page using react-tooltip

### ISSUE THREAD

**Issue by smancang** [wwayne/react-tooltip#41]
It says "Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.",
And when I jump up to the Code I find that the code "document.getElementsByTagName('head')[0].removeChild(tag);" in the react-tooltip.js.
I debug it finding that  it's called many times,maybe because I have many tooltips in the page.So,I think it need a null judgement here.

**Comment by wwayne** [comment]
Fixed. Thanks : )
