### ISSUE TITLE
behavior changed after update from 0.7.3 to 0.8.1

### ISSUE THREAD

**Issue by Fraina** [wwayne/react-tooltip#42]
here is the dom structure:
```js
<div>
  <Content data-tip="content">
    <SubContent>
      <SubElement></SubElement>
    </SubContent>
  </Content>
  <ReactTooltip place="bottom" effect="solid" />
</div>
```

With 0.7.3, when I mouse over `<Content>` area or its subelements, the tooltip component will positioned relative to `<Content>` element.

But with 0.8.1, the tooltip will positioned relative to the current mouseover target. e.g. If I mouse over `<SubContent>` element, the tooltip will moved to the bottom of `<SubContent>`.

Just wonder if I have some misunderstanding about default behavior.

**Comment by wwayne** [comment]
Looks more like a bug of the latest react-tooltip, I will check this later, thanks for report.
