### ISSUE TITLE
The dependency to sanitize-html imports all postcss dependencies

### ISSUE THREAD

**Issue by jgerlier** [wwayne/react-tooltip#424]
Since the version `0.8.1`, the `sanitize-html` dependency has been added, but this package is designed for node and depends on the `postcss` package.
This causes two issues : 
* an addition of 517 KB to the bundle size.
* ES6 code imported

Would it be possible for you to avoid this dependency ?

Thank you

**Comment by aronhelser** [comment]
It was added to avoid a possible security concern with cross-site scripting - is there another package to do html-sanitize that is smaller/better?
