### ISSUE TITLE
lots of findDOMNode invariant warnings since 3.8.x release

### ISSUE THREAD

**Issue by occamsraiser** [wwayne/react-tooltip#430]
Hi folks. We've been using this library to power our website tooltips in React for about two years. We use Sentry.io to track front end errors experienced by visitors, and I've noticed a huge uptick in findDOMNode Invariant Violation warnings since we deployed 3.8.x.  Can anyone else corroborate? We use findDOMNode in two spots in our codebase and I'm seeing these warnings from most of our pages that have these tooltips on them.

The specific error is "findDOMNode was called on an unmounted component"

**Comment by stahlmanDesign** [comment]
If you use strict mode, React warns that findDOMNode is deprecated. It is used in react-tooltip and would be good if it were refactored to use the proposed solution of adding "a ref directly to the element you want to reference" — I haven't looked into exactly what to do to fix this:
`
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ReactTooltip which is inside StrictMode. Instead, add a ref directly to the element you want to reference.
`

**Comment by stahlmanDesign** [comment]
Relates to #331 describing possible solution

**Comment by aronhelser** [comment]
If you want to try fixing react-tooltip, I'll gladly accept a PR!

**Comment by nadineshmo** [comment]
Any update on this PR? I'm also getting the issue "findDOMNode was called on an unmounted component" raised by the first commenter. Not sure if this PR will fix this, or just the strict mode deprecation warning?

**Comment by Andsbf** [comment]
I wonder the same @nadineshmo, **apparently** it only fix the strict mode thing.

**Comment by Andsbf** [comment]
@thanks for merging it in @aronhelser , will a new tag be released with this change?

**Comment by oudia15** [comment]
I am still having this issue, Has a new tag been released with the fix ?
