### ISSUE TITLE
Doesn't work inside CSS transformed elements.

### ISSUE THREAD

**Issue by trusktr** [wwayne/react-tooltip#434]
It's not working when the container (containing the content and the ReactTooltip) is transformed (f.e. scaled). Basically it is the same problem as this: https://github.com/FezVrasta/popper.js/issues/686 (the first codepen about the transforms, see solution concept description there).

Basically, both libs (react-tooltip and popper.js) are not taking into consideration transformed containers.

Try applying a `transform:scale()` to your elements and you will see the issue. F.e. `transform: translateX(-149px) scale(0.8);` to the outer container.

It would be great to have this work!

**Comment by Rogger794** [comment]
Hi @trusktr, could you try the new release 3.11.6 and let me know if it works.

**Comment by Rogger794** [comment]
Could be reopen if it presents again this case
