### ISSUE TITLE
Request: some Tooltips randomly not showing up on Mac

### ISSUE THREAD

**Issue by oladhari** [wwayne/react-tooltip#436]
On Linux it works without problems,This bug only affects Mac OS and iOS users
when accessing the web-page some tooltips doesn't show up
when deleting cache the problem remains same only after refreshing the page without deleting the cache  it works fine and all tooltips show up

**Comment by oladhari** [comment]
is there any hint or advice?

**Comment by oladhari** [comment]
@wwayne I would like to have any advice to treat this problem if you don't mind , thank you

**Comment by wwayne** [comment]
@oladhari one case I can imagine is, you load some data after ReactTootip loaded, for example:
```
 constructor () {
   this.state = {
       isLoaded: false
   }
 }

 componentDidMount () {
   goFetchData().then(() => {
      this.setState({
         isLoaded: true
      })
   })
 }

 render ( ) {
   const { isLoaded } = this.state 
   return (
       <div>
           { isLoaded && <a data-tip='sth'>show me when data loaded</a> }
           <ReactTooltip />
       </div>
   )
 }
```
so you can:
1. call ReactTooltip.rebuild() after data loaded
2. put `<ReactTooltip />` into the later-loaded component

is it solve ur problem? sorry I'm not active on maintaining this project at the moment
