### ISSUE TITLE
Global tooltips don't work for items that load after page loads

### ISSUE THREAD

**Issue by milesmeow** [wwayne/react-tooltip#437]
I have a page that loads in two stages.

First stage:
Render the main content after the data returns. This first render includes items that will use global tooltips.

Example of a global tool tip that's used everywhere on the page.
`<ReactTooltip id='info-tooltip' effect='solid'><TooltipText>My tooltip text</TooltipText>`

Example of an Item that uses the global tooltip.
`<StatIcon data-tip data-for="info-tooltip" src={imageURL} />`

Second stage:
The second part of the page that loads depends on an API call that usually takes a few seconds.
When that data comes back I render content that also uses the global tooltip.
`<StatIcon data-tip data-for="info-tooltip" src={imageURL} />`

Here's the weird behavior.  The icons that results from the second stage rendering does not display the global tooltip when I mouse over them.

Here's what I did to 'hack' around this issue.
I moved where I render the `<ReactTooltip>` to the second stage and now the tooltip shows for all icons.  However, b/c I'm loading the global tooltips in the second stage, the icons rendered in the first stage doesn't show tooltips until the second part of the page loads.

Is there something that I can do to render the global tooltip `<ReactTooltip>` in the first part of the page load and have it show up for icons that gets rendered in the second part?

Does react-tooltip somehow gets an inventory of items with `data-tip` and `data-tip-for` attributes when it first renders to determine which items it needs to show tooltips for?

**Comment by aronhelser** [comment]
Have you tried the .rebuild() method?

**Comment by aronhelser** [comment]
Great! glad it worked.
