### ISSUE TITLE
ReactTooltip element contents displayed if another tooltip no longer rendered

### ISSUE THREAD

**Issue by dpwrussell** [wwayne/react-tooltip#44]
If a tooltip on the page is no longer rendered then the contents of the other tooltips are rendered to the page in their dom location. This will happen if the tooltip element itself is no longer rendered, or if an element containing a tooltip is no longer rendered.

The problem corrects itself for all tooltips when another tooltip is moused over.

This example has 3 divs with mouseover tooltips. It also has 3 buttons which toggle the display of that tooltip off. When toggling the display of one of the tooltips off, the content of the other two is displayed until you mouseover one of the remaining tooltip enabled divs.

``` javascript
import React from 'react';
import ReactDOM from 'react-dom';
import ReactTooltip from 'react-tooltip';

class TooltipProblem extends React.Component {
  constructor(props) {
      super(props);

      this.state = {
        showTooltip1: true,
        showTooltip2: true,
        showTooltip3: true
      }

      // Prebind 'this' to methods
      this._handleClick1 = this._handleClick1.bind(this);
      this._handleClick2 = this._handleClick2.bind(this);
      this._handleClick3 = this._handleClick3.bind(this);
  }

  _handleClick1() {
    this.setState(
      {
        showTooltip1: !this.state.showTooltip1
      }
    )
  }

  _handleClick2() {
    this.setState(
      {
        showTooltip2: !this.state.showTooltip2
      }
    )
  }

  _handleClick3() {
    this.setState(
      {
        showTooltip3: !this.state.showTooltip3
      }
    )
  }

  render() {

    return (
      <div>

        <div data-tip
             data-for={"tooltip1"}>Mouseover1</div>
        {this.state.showTooltip1 &&
          <ReactTooltip id={"tooltip1"} place="bottom" type="dark" effect="solid">
            <p>My tooltip 1</p>
          </ReactTooltip>
        }
      <input type="button" onClick={this._handleClick1} value="Toggle 1" />

      <br /><br />

      <div data-tip
           data-for={"tooltip2"}>Mouseover2</div>
      {this.state.showTooltip2 &&
        <ReactTooltip id={"tooltip2"} place="bottom" type="dark" effect="solid">
          <p>My tooltip 2</p>
        </ReactTooltip>
      }
    <input type="button" onClick={this._handleClick2} value="Toggle 2" />

    <br /><br />

    <div data-tip
         data-for={"tooltip3"}>Mouseover3</div>
    {this.state.showTooltip3 &&
      <ReactTooltip id={"tooltip3"} place="bottom" type="dark" effect="solid">
        <p>My tooltip 3</p>
      </ReactTooltip>
    }
    <input type="button" onClick={this._handleClick3} value="Toggle 3" />

      </div>
    );
  }

}


(function() {
    'use strict';

    ReactDOM.render(<TooltipProblem />, document.getElementById('app'));
})();

```

This is a simplified example, toggling the actual tooltips on/off, but as I mentioned, it happens if any tooltip is no longer rendered. So if you use tooltips in two different components and then one of those components is no longer rendered, you see this problem.

Tooltip displaying correctly:

![before](https://cloud.githubusercontent.com/assets/1889043/10732551/fdbd6420-7bd0-11e5-9d0a-b61cab0b4b83.png)

After toggling off the display of a tooltip element (3 in this case):

![after](https://cloud.githubusercontent.com/assets/1889043/10732550/fdbb9848-7bd0-11e5-978d-6ce3db52728b.png)

As you can see, "My Tooltip 1" and "My Tooltip 2" are rendered to the screen, which should not happen.

Cheers

**Comment by wwayne** [comment]
@dpwrussell  
Thanks for your detailed explanations. Yes, I can see the problem.

I suppose that you need a function to unbind(remove) a specific tooltip, because I don't think the way you control the tooltip's display is convenient or as my expected.

So I will gonna build a function of controlling specific tooltip's display(`ReactTooltip.unbind(tooltipId)` ?), do you think it would be useful for your use?

**Comment by dpwrussell** [comment]
Hiding the tooltip like I do in the example above does seem a bit weird. But if two components (say, from npm) were both making use of react-tooltip then this would be a problem if either of them was to not be rendered.

So, right now if you unmount any tooltip, they all unbind? Would it not make sense to only unbind the tooltips with that same id in `componentWillUnmount`?

**Comment by wwayne** [comment]
This is because the style of react-tooltip will be removed after unmount.
Now I keep the style because I don't think the previous process is necessary.

But I still think it is a bit weird of this example, re-open this issue if we can find a more 'delicate' way
