### ISSUE TITLE
decrease bundle size

### ISSUE THREAD

**Issue by Abdisalan** [wwayne/react-tooltip#441]
![screen shot 2018-10-04 at 12 13 38 pm](https://user-images.githubusercontent.com/6256142/46487807-f4db4000-c7ce-11e8-9bbc-ba59c12b2887.png)

Could there be a way to pick which parts of the tooltip you want to decrease this bundle size? I'm not using  80% of the features and its much too large.

**Comment by aronhelser** [comment]
Please see issue #429 - the sanitize html made the bundle much bigger. I think we're going to remove it soon. In the meantime, you can try version 3.8.0, right before the sanitization.
