### ISSUE TITLE
Tooltip should hide when scroll start, not when it ends.

### ISSUE THREAD

**Issue by Edulopez** [wwayne/react-tooltip#448]
When you set the tooltip to hide on scroll it waits for the scroll to end instead of when it start.

Current configuration:
```
<ReactTooltip
          place={this.props.toolTipPosition}
          id={this.props.id}
          type={this.props.type}
          eventOff="mouseleave scroll mousewheel blur"
          effect="solid"
/>
```

Proof:
![tooltipissue](https://user-images.githubusercontent.com/5016793/47262248-38ad9500-d4b1-11e8-9eac-3d0564324e05.gif)

**Comment by Edulopez** [comment]
Manage to solve part of the issue when scrolling.

This issue was related of the use of the EventOff property. This can only work if you setup the event property. If you set up some other events you may remove the scroll issue

```
<ReactTooltip
          place={this.props.toolTipPosition}
          id={this.props.id}
          type={this.props.type}
          event="mouseover mouseenter"
          eventOff="mouseleave mouseout scroll mousewheel blur"
          effect="solid"
        />

```

The issue is still there because you can do scroll down/up using the arrow keys in the keyboard.

**Comment by aronhelser** [comment]
Take a look at the scrolling example - if you remove `scroll` from the eventOff list and follow the setup there, does it resolve the issue?

**Comment by Edulopez** [comment]
Nope. It does not. 

It works with the scroll button but not with the arrow keys.

**Comment by aronhelser** [comment]
When I try on the demo page: https://react-tooltip.netlify.com/

and I click inside the scrolling panels so I can use the arrow keys, the tooltip hides as expected when using the arrow keys - the first panel hides, the second one doesn't.

Did you set `data-iscapture='true'` for your target, as shown in the example?

Otherwise IDK what might be wrong? If you can investigate or propose a fix, we can get it released....

**Comment by ThisIsRoy1** [comment]
@aronhelser data-iscapture='true' worked great for me tnx

**Comment by aronhelser** [comment]
Latest comment had success, so closing, thanks!
