### ISSUE TITLE
npmjs.com documentation formatting

### ISSUE THREAD

**Issue by dpwrussell** [wwayne/react-tooltip#45]
The README.MD formatting goes a bit haywire on npmjs.com. Looks fine on GitHub though.

![npmjs doc](https://cloud.githubusercontent.com/assets/1889043/10732795/1cf7767c-7bd2-11e5-88ee-675512d29fdc.png)

**Comment by wwayne** [comment]
Looks npm doesn't have a good support for this table format, I've checked other npm component, and they all have the same problem. So I don't want to make change on this, at least for now.
