### ISSUE TITLE
Seeing href attribute eslint error when using `react-tooltip` with React 16.6.3

### ISSUE THREAD

**Issue by sunweiyang** [wwayne/react-tooltip#456]
To use `react-tooltip`, we are instructed to use `<a data-tip data-for={"somestring"}><OurTooltippedComponent></a>`, and to do so without defining `href`. When using the latest React (16.6.3), we see the following warning when running `npm start`:

```
Compiled with warnings.
./src/components/HomeRoute/index.js
  Line 181:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
```

As discussed elsewhere, we can edit our personal `.eslintrc` files [to make it go away](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details), but this doesn't seem very clean. Can this warning issue be addressed within `react-tooltip`?

**Comment by aronhelser** [comment]
The <a> tag is just a convenient wrapper in this case - a <span> tag will work just as well. Let me know if this works for you.

**Comment by codenoobforreal** [comment]
> To use `react-tooltip`, we are instructed to use `<a data-tip data-for={"somestring"}><OurTooltippedComponent></a>`, and to do so without defining `href`. When using the latest React (16.6.3), we see the following warning when running `npm start`:
> 
> ```
> Compiled with warnings.
> ./src/components/HomeRoute/index.js
>   Line 181:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
> ```
> 
> As discussed elsewhere, we can edit our personal `.eslintrc` files [to make it go away](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details), but this doesn't seem very clean. Can this warning issue be addressed within `react-tooltip`?

the same!
maybe just add a wrapper to your react element or component will solve this problem
this one has eslint warning
```
<ReactTooltip id="unit" className={styles.tooltip} />
<Unit pop={item} data-tip={item} data-for="unit"/> 
```
this one is ok!
```
<ReactTooltip id="unit" className={styles.tooltip} />
<div data-tip={item} data-for="unit">  
    <Unit pop={item} /> 
</div>
```
