### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by marcovdijk** [wwayne/react-tooltip#46]
In React 0.14 you can get a DOM node by directly calling the ref. See the [React blog](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs). Now i'm getting warnings in the console like this: Warning: **React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.**

**Comment by wwayne** [comment]
react-tooltip used react-dom to support 0.14 since 0.8.
And I've tested in my end, there is no warning message.

**Comment by marcovdijk** [comment]
My bad, I updated through NPM but had a wrong setting in my package.json.
