### ISSUE TITLE
Tooltip does not hide when dragging elements with ReactDnD

### ISSUE THREAD

**Issue by actraiser** [wwayne/react-tooltip#460]
I use ReactDnD to move elements around the page. I want to show a tooltip when hovering over such an element before drag starts. When dragging starts, the tooltip should disappear. 

What happens right now, is, that as soon as I start dragging, the tooltip will not hide until I dropped the item.

My item component looks like this:

```
<React.Fragment>
  <DraggableItem
    data-tip
    data-for: "item_1",
    id="item_1"
    ref={(instance: any) => connectDragSource(instance)}
  />
  <ReactTooltip id="item_1">
    some example content
  </ReactTooltip>
</React.Fragment>

```

Any hints on how to make the tooltip disappear when dragging starts would be appreciated.

Greets
-act

**Comment by danherd** [comment]
Any chance you can share your solution @actraiser?

**Comment by semosem** [comment]
@actraiser can share your solution

**Comment by faz919** [comment]
@actraiser shot in the dark here but I'm having the same issue if you found a solution.

**Comment by gabrieljablonski** [comment]
@faz919 feel free to open a new issue if you're experiencing that with v5.

**Comment by faz919** [comment]
I found the documentation for that use case and it worked well. Thank you!

**Comment by gabrieljablonski** [comment]
@faz919 please share so other people can use it as well in the future.
