### ISSUE TITLE
Is there a way to hide the arrow of the tooltip?

### ISSUE THREAD

**Issue by dmc1985** [wwayne/react-tooltip#468]
I looked at the html and I did not see a class that was explictly linked to the arrow. Is there a CSS rule that I can add to remove the arrow of the tooltip?

**Comment by dmc1985** [comment]
I was able to remove the arrow by adding the following css rules: 
```
<css class added with className prop>.__react_component_tooltip.place-left::after {
    border-left: 0 solid <color of rest of border> !important;
}

<css class added with className prop>.__react_component_tooltip.place-right::after {
    border-right: 0 solid <color of rest of border> !important;
}

<css class added with className prop>.__react_component_tooltip.place-top::after {
    border-top: 0 solid <color of rest of border> !important;
}

<css class added with className prop>.__react_component_tooltip.place-bottom::after {
    border-bottom: 0 solid <color of rest of border> !important;
}
```

**Comment by conradks** [comment]
I'm not sure when it was added, but I used the property arrowColor and set it to transparent. That seemed to do it for me.

**Comment by kanke** [comment]
> I'm not sure when it was added, but I used the property arrowColor and set it to transparent. That seemed to do it for me.

Please do you have a code snippet for this?

**Comment by conradks** [comment]
`     <ReactTooltip arrowColor="transparent">
        Your tool tip stuff here.
      </ReactTooltip>`

**Comment by conradks** [comment]
> > I'm not sure when it was added, but I used the property arrowColor and set it to transparent. That seemed to do it for me.
> 
> Please do you have a code snippet for this?

`<ReactTooltip arrowColor="transparent"> Your tool tip stuff here. </ReactTooltip>`

**Comment by DeLm0re** [comment]
> > > I'm not sure when it was added, but I used the property arrowColor and set it to transparent. That seemed to do it for me.
> > 
> > 
> > Please do you have a code snippet for this?
> 
> `<ReactTooltip arrowColor="transparent"> Your tool tip stuff here. </ReactTooltip>`

However, this will make an arrow filled with the color of the borders. Seems impossible to hide it in a casual way if you are using borderColor prop

**Comment by ridak** [comment]
This seems to have worked for me (though I haven't tested this exhaustively yet). It's similar to dmc1985's approach though I was able to get away with just one rule that works for all the different placements.
```
<css class added with className prop>::before {
  border: 0 !important;
}
```

**Comment by justinherrera** [comment]
`<span data-tip="test" data-class="tool-tip"></span>`

```
.tool-tip::before {
  border-right: none !important;
}
```

**Comment by YarPetru** [comment]
I've found the sipliest way. Just add noArrow attribute like this:
      <Tooltip id="tooltip" className={s.tooltip} place="bottom" noArrow />
