### ISSUE TITLE
My tooltip does not appear

### ISSUE THREAD

**Issue by FruitAndAShape** [wwayne/react-tooltip#469]
I have...

```
import ReactTooltip from 'react-tooltip'

<ReactTooltip effect="solid" />

<th data-tip={text} ... />

```
Just like the instructions say. If I uncheck a bunch of CSS rules then I can see the tool tip sitting empty on the screen.

But it doesn't appear when I roll over the <th>. What reason could there be for this?

**Comment by aronhelser** [comment]
If your item is not a child of the ReactToolTip, you need to use the `data-for='happyFace'` property on your item, and the `id='happyFace'` property on the ReactToolTip, so they link up. It's shown in the first example. I'll take a look at the code at the top and see why the first example code shown is not correct.

**Comment by FruitAndAShape** [comment]
That didn't fix it unfortunately.

**Comment by FruitAndAShape** [comment]
It works if I add a tooltip to another page element. Why doesn't it like my generated table header cells?

**Comment by aronhelser** [comment]
It's because your generated table cells aren't present when the Tooltip is
created. You need to call `.rebuild()` after they are created so the
tooltip can discover them.

**Comment by FruitAndAShape** [comment]
Where is the optimum place to do this? After every render?

**Comment by FruitAndAShape** [comment]
I did this...

```
componentDidUpdate() {
   ReactTooltip.rebuild();
}
```
