### ISSUE TITLE
Feature: ReactTooltip.show()

### ISSUE THREAD

**Issue by jcalfee** [wwayne/react-tooltip#47]
I have an important tooltip that I want to show programmatically.  I could then set a timeout and ReactTooltip.hide() it .. Best if the hover would prevent it from being hidden.  

Do you have an example for this?  Should I try to capture an event and pass it to ReactTooltip.showTooltip (e) ?

**Comment by wwayne** [comment]
Now the react-tooltip doesn't support `show programmatically`, let me do some develop next.

**Comment by marina-marina** [comment]
In addition to that, would be nice if we could choose the way it's triggered - on hover, click or event.

**Comment by wwayne** [comment]
Thanks @Sly777
**v0.9.0** start to support customer event
`<ReactTooltip event='click' />` or `<a data-event='click' data-tip='tooltip'></a>`

**Comment by OAGr** [comment]
Did this fix the original issue with ReactTooltip.show()?  It seems like the .show() method is still missing to me.

**Comment by wwayne** [comment]
I didn't build the `.show` method, instead there have custom event to trigger tooltip to show up.

**Comment by OAGr** [comment]
Thanks for confirming.

**Comment by craigcosmo** [comment]
how can I trigger custom event? 

For example: 

```html
<a data-event='specialhat' data-tip='tooltip'></a>
```
How to trigger such event?

**Comment by wwayne** [comment]
Behind `data-event='event'` is `document.addEventListener('event', () => {...}, false)`, so it only support those HTML DOM event like click, doubleClick, etc... so react tooltip can't trigger your custom event `specialhat`

**Comment by craigcosmo** [comment]
ah I see. so in case I want to display error tool tip when user input invalid data, what's the best way to trigger it in this case? 

It can not be click, because it's an input type text. users click it at the beginning.

**Comment by wwayne** [comment]
@craigcosmo Looks there's no way to satisfy your requirement at the moment, you may need a static method like `ReactTooltip.show('tooltipId')`, I don't know when I have time to build such function..

**Comment by RanjithNair** [comment]
@craigcosmo : Were you able to implement show method? Just wanted to check before i give it a try. 
@wwayne : Is this something which is still in your radar?

**Comment by craigcosmo** [comment]
Not yet, if you do, please notify once you got. Im also interested





On Thu, Jun 16, 2016 at 2:29 AM +0700, "Ranjith Nair" <notifications@github.com> wrote:












@craigcosmo : Were you able to implement show method? Just wanted to check before i give it a try. 

@wwayne : Is this something which is still in your radar?

**Comment by wwayne** [comment]
No, I don't have any plan on this at the moment. It's not that easy to implement this feature, much less we should have to consider if the user want to show multi tooltip at the same time.

**Comment by payner35** [comment]
this show() feature would be very useful to highlight icons / locations on a google map. Please let me know how you get on.

**Comment by wwayne** [comment]
This has been supported since `3.1.5`, but you have to specific the target element, for example:

```
import {findDOMNode} from 'react-dom'
import ReactTooltip from 'react-tooltip'

<p ref='foo' data-tip='tooltip'></p>
<button onClick={() => { ReactTooltip.show(findDOMNode(this.refs.foo)) }}></button>
<ReactTooltip />
```

**Comment by craigcosmo** [comment]
thank you so much for making this!

**Comment by DeepanshuTaneja** [comment]
it shows  _XflowTooltip2.default.show is not a function.
 I called this function on image click.

**Comment by wwayne** [comment]
@DeepanshuTaneja No idea why you got _XflowTooltip2, but I didn't find `_XflowTooltip2` in this repo

**Comment by ac1dr3d** [comment]
thank you!

**Comment by addijhaq** [comment]
i cannot get tool tip to show when onDrag event is set.

`data-event='drag'` `data-event='ondrag'` none of these work.... these are HTML DOM events.... nothing special here.

**Comment by mymywang** [comment]
@wwayne Thanks for creating the library! I have a question about your example to use `ReactTooltip.show(target)`. Why is the type of the input `target` string? The return type of `findDOMNode` is not string, so I wonder if it still works now:
```
<button onClick={() => { ReactTooltip.show(findDOMNode(this.refs.foo)) }}></button>
```
I tried to use `React.useRef` hook, but it usually refers to a DOM element instead of string.

I also looked at the source code, and it seems that the way it works is to create an event by (https://github.com/wwayne/react-tooltip/blob/master/src/decorators/staticMethods.js#L15):
```
event = document.createEvent("Event");
event.initEvent(eventName, false, true, { target });
```
However, I tried it out and the function `initEvent` only accepts 3 input parameters.

All I'm trying to figure out is how to use `ReactTooltip.show(target)` to manually show the tooltip. Could you provide another example with `React.useRef`, or add details on what `target` should be? Thank you very much!

**Comment by ZDTaylor** [comment]
@mymywang Just ran into this. You can use this for `React.useRef`:
```
ReactTooltip.show(tooltipTarget?.current);
```

Not sure if I did something wrong though, but I had to set `data-event="fakeEvent"` to stop the default hover behavior.

**Comment by mymywang** [comment]
@ZDTaylor Thanks. I tried it but typescript complains that the input passed into `ReactTooltip.show()` should be a string. I didn't try to override the type error though. If it could work, there's probably just an issue in type definitions.

**Comment by tim-phillips** [comment]
I had to do the following to stop from TS complaining:

```ts
const toolTipRef = useRef(null);
useEffect(() => {
  ReactTooltip.show((toolTipRef?.current as unknown) as Element);
});
```
