### ISSUE TITLE
Question: Why does hovering on element cause component to update

### ISSUE THREAD

**Issue by CWSites** [wwayne/react-tooltip#471]
I am using react-tooltip inside of react-table and some of my cells have a tooltip attached while others do not. When I hover over cells on my table that do not have a tooltip my table component doesn't update, however if I hover over a cell which does have a tooltip my table component updates on every movement of my mouse no matter how small.

Is the constant redrawing/updating because of the tooltip position changing? It seems like there would be a more performant way to handle tooltips while a mouse is moving around on the triggering element. Is there a way to keep the tooltip in a static position rather than following my mouse?

**Comment by aronhelser** [comment]
Yes, you can have a static position, which is probably what you want - take a look at the examples.

**Comment by CWSites** [comment]
@aronhelser I looked but didn't see anything showing that, can you point me in the right direction?

**Comment by aronhelser** [comment]
Sure! On the example site: https://react-tooltip.netlify.com/
at the very top, choose the 'solid' setting instead of the 'floating'.

**Comment by aronhelser** [comment]
Also, if I understand correctly, even if your component re-renders, the tooltip will be the only thing that changes, so React should leave the DOM alone for the other pieces of your component. Hopefully. :)

**Comment by CWSites** [comment]
Thank you, I had some other stuff inside of `componentDidUpdate()` which was firing every time that I my mouse moved which was very frustrating. `solid` works wonders now and it only updates when I first hover over the popup. 

Cheers!
