### ISSUE TITLE
delayHide create confusion when hidding tooltip due to a scroll event

### ISSUE THREAD

**Issue by metroSetenta** [wwayne/react-tooltip#474]
When you want to use the mouse in the tooltip information, and set the delayHide option, this should not be applied when scrolling and scrollingHide is set to true, it creates confusion because the tooltip is over another element. Maybe delayHide not should be applied when hidding due to a scroll event.

![tooltip scroll error](https://user-images.githubusercontent.com/2429109/53893050-b8d23280-402d-11e9-8510-e8711b4ef312.gif)

**Comment by kashifshamaz21** [comment]
I'm also facing this same issue wherein, when user scrolls the window, the open tooltip doesn't hide. 
following is my tooltip usage:

```
<ReactTooltip data-event='click' id={tooltipId} delayHide={500} place="bottom" clickable={true}
                  type="light" effect="solid">
    //<some component />
</ReactTooltip>
```

Will see if i can figure out a fix for this while i use this library. Btw, I really liked the way this tooltip component is designed and implemented. Kudos to all the developers contributing to this. 

Cheers.

**Comment by tihuan** [comment]
Hey all! A coworker and I figured out a quick fix for this. PTAL!

https://github.com/wwayne/react-tooltip/pull/504 thank you!
