### ISSUE TITLE
Applying style to `place-top` or `place-left` doesn't work as expected. 

### ISSUE THREAD

**Issue by kuldeep-taroko** [wwayne/react-tooltip#478]
Component
```
<ReactTooltip className={styles.customTheme} id={id} place={placement} effect="solid"> 
    {children}
</ReactTooltip>
```

SCSS
```
.customTheme {
  color: #ff6e00 !important;
  background-color: orange !important;

  &.place-top {
    &::after {
      border-top: 6px solid orange !important;
    }
  }
}
```
Result
![Screen Shot 2019-03-20 at 12 39 54 PM (2)](https://user-images.githubusercontent.com/46096889/54659591-73bdfe00-4b0d-11e9-911d-cd4b1f7d6417.png)

Issue
I am using CSS Modules in my app. Because of which the arrow color is not changed as expected.

I tried using `:global`, but it didn't work.
```
:global(.customTheme) {
   &.place-top {
    &::after {
      border-top: 6px solid orange !important;
    }
  }
}
```

**Comment by kuldeep-taroko** [comment]
This worked for me.

:global {
  .place-top {
    &::before {
      border-top: 8px solid $white-six !important;
    }

    &::after {
      border-top: 6px solid $pale-grey-four !important;
    }
  }
}


Thanks

**Comment by SaadEla** [comment]
hiii how we can change css props like padding in a tooltip?
