### ISSUE TITLE
React can't find the root component node for data-reactid value - it probably means you've loaded two copies of React on the page

### ISSUE THREAD

**Issue by opensourcegeek** [wwayne/react-tooltip#48]
I'm getting this error when I add <ReactTooltip /> into my component. Any ideas why?

**Comment by praneybehl** [comment]
I am getting the same too. No idea what's going on. Can you please help?

**Comment by praneybehl** [comment]
Alright found and fixed. Wanted to mention here, @opensourcegeek make sure you require('react-dom'), op missed to mention it in the docs. 
Here is a reference in the example: https://github.com/wwayne/react-tooltip/blob/master/example/src/index.js
Hope it helps!

**Comment by wwayne** [comment]
Did you mean `import {render} from 'react-dom'`?
This is required by React since 0.14
