### ISSUE TITLE
How to use tooltip in function components with hooks (React 16.8+)

### ISSUE THREAD

**Issue by martinschayna** [wwayne/react-tooltip#485]
This doesn't work for me:
```js
const Panel = props => {
  React.useLayoutEffect(() => ReactTooltip.rebuild());
  return <div title="Tooltip">Hello, world!</div>;
}
```
Class components work as expected:
```js
class Panel extends React.Component {
  componentDidMount() {
    ReactTooltip.rebuild();
  }
  componentDidUpdate() {
    ReactTooltip.rebuild();
  }
  render() {
    return <div title="Tooltip">Hello, world!</div>;
  }
}
```

**Comment by necholasg** [comment]
In your example, you would need to use useEffect.

`const Panel = props => {
  useEffect(()=>{
        ReactTooltip.rebuild();
    }, [props]);

  return <div title="Tooltip">Hello, world!</div>;
}`

That will watch for prop changes and rebuild when necessary.

**Comment by martinschayna** [comment]
Yep, now it works, I had to pass the second parameter with array of related props to `useEffect`. Thanks.
