### ISSUE TITLE
Replace legacy life-cycle events with new ones

### ISSUE THREAD

**Issue by mentierd** [wwayne/react-tooltip#488]
Hello,

I'm very interested in switching over to this library from rc-tooltip as it seems to be unmaintained. One issue that I'm facing with both of your libraries is the use of componentWillMount / componentWillReceiveProps.  

Preventative maintenance should be performed to replace these older life cycle methods with their newer equivalents: componentDidMount / static getDerivedStateFromProps.  The reason is that these life cycle events will not be supported with react fiber / concurrent rendering.

**Comment by stahlmanDesign** [comment]
react-tooltip is one of the only libraries I am using that still throws deprecation warnings (in strict mode)
![Capture d’écran, le 2019-05-02 à 17 41 13](https://user-images.githubusercontent.com/972804/57108707-8f6a1600-6d01-11e9-828a-435b71dc2f82.png)

**Comment by aronhelser** [comment]
A PR will gladly be accepted!

**Comment by Rogger794** [comment]
Already replace those methods. I will close this issue.
