### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by usama-asfar** [wwayne/react-tooltip#492]
![Capture](https://user-images.githubusercontent.com/42825498/58145896-81a91000-7c71-11e9-8460-c54aea53cfe0.PNG)

**Comment by aronhelser** [comment]
Looks like an ordering issue - try looking at the z-index of the green pane compared to the tooltip.

**Comment by usama-asfar** [comment]
> Looks like an ordering issue - try looking at the z-index of the green pane compared to the tooltip.

what is the tooltips z-index?

**Comment by aronhelser** [comment]
https://github.com/wwayne/react-tooltip/blob/master/src/index.scss#L69
you can also check with the browser's debugger, if you trigger a hover
event on the item with a tooltip.
