### ISSUE TITLE
Unable to get property 'target' of undefined or null reference in globalShow

### ISSUE THREAD

**Issue by abraztsov** [wwayne/react-tooltip#498]
Hi react-tooltip team 👋

Sometimes an error occurs in Edge 18.17763 browsers

`TypeError: Unable to get property 'target' of undefined or null reference`

in

`./node_modules/react-tooltip/dist/decorators/staticMethods.js in e.prototype.globalShow at line 43:1`

here

```
target.prototype.globalShow = function (event) {
    if (this.mount) {
      // Create a fake event, specific show will limit the type to `solid`
      // only `float` type cares e.clientX e.clientY
      var e = { currentTarget: event.detail.target }; // <––– error occurs here
      this.showTooltip(e, true);
    }
  };
```

**Comment by DalerAkhmetov** [comment]
Hi. I have also this error in Edge 18.17763

**Comment by aronhelser** [comment]
Can you submit a fix?

**Comment by Jarch09** [comment]
any update on this? I just started having the same issue...

Perhaps I can submit a fix if no one else has gotten around to it
