### ISSUE TITLE
Moving mouse horizontally over element's content makes tooltip flicker

### ISSUE THREAD

**Issue by sebmor** [wwayne/react-tooltip#51]
Take a "solid top/bottom" example http://wwayne.com/react-tooltip/ and move your mouse left-right, and the right side will flicker.

**Comment by wwayne** [comment]
Just tried as what you said, I don't have this issue.
Maybe that's because you move the mouse out of element which have tooltip then draw the mouse back.

reopen if I misunderstand something.

**Comment by sebmor** [comment]
Recorded it http://cl.ly/3J0l273s2q2x
Had to put width:auto/remove width parameter to consistently reproduce it this time.

**Comment by wwayne** [comment]
Find this problem in retina mac, reopen this ticket

**Comment by wwayne** [comment]
No idea how to fix, and only exist in Retina, people won't notice this unless move slowly intentionally, closing
