### ISSUE TITLE
overridePosition not providing currentEvent when initially showing tooltip

### ISSUE THREAD

**Issue by bryantung** [wwayne/react-tooltip#513]
As stated on the API, we should expect `overridePosition` to have `currentEvent` object as second param, but instead we get `currentTarget` and all the other following params has been shifted.

https://github.com/wwayne/react-tooltip/blob/11ee685da575058099ae394e4210da120f1a215f/src/index.js#L318

**Comment by Rogger794** [comment]
@bryantung could you please check the last version?

**Comment by bryantung** [comment]
@Rogger794 yes the latest release fixed it, thanks!
