### ISSUE TITLE
should support custom color & font size, font family

### ISSUE THREAD

**Issue by liesislukas** [wwayne/react-tooltip#52]
would like to use branding color, not defaults as now. Also font size & font family.

**Comment by wwayne** [comment]
You can use the `class` option
```
in your JS file:
<ReactTooltip class='mySepecialClass' /> or <p data-class='mySepecialClass' data-tip='tooltip'></p>

in your CSS file:
.mySepecialClass {
  background: yellow !important;
  font-size: 100px !important;
}
```

**Comment by bogdanbrezuica** [comment]
Hello @wwayne 

I also need to change the background color, but your (old) solution above doesn't also change the border arrow color. And I can't find out where the tooltip will be displayed (top, bottom etc) when the element is close to the viewport margins.

Any idea on how to quickly solve this?  Have you considered adding a "background" prop on ReactTooltip? 

Thanks!

**Comment by wwayne** [comment]
@bogdanbrezuica current solution is somewhat ugly:
```
<a data-tip='custom theme'>(･ω´･ )́)</a>
<ReactTooltip class='customeTheme'/>
 .customeTheme {
   color: #ff6e00 !important;
   background-color: orange !important;
   &.place-top {
     &:after {
       border-top-color: orange !important;
       border-top-style: solid !important;
       border-top-width: 6px !important;
     }
   }
}
```
You can check the `Theme and delay` part in example page

**Comment by bogdanbrezuica** [comment]
Thanks for the fast reply. Yes, it is somewhat ugly but it definitely saves the day! Also, good job on this library, I like how fast it is!

**Comment by eisenjulian** [comment]
Hi @wwayne I was wondering if there is a workaround as I need to set the fontFamily using an inline style. The reason is that in my use case the style can be configured by my end-user.

**Comment by wwayne** [comment]
@eisenjulian For the moment, no, the only way you can try is through the className option

**Comment by diegoolavarria** [comment]
@botrepper how did you change the color of the arrow?

**Comment by andyjamesduncan** [comment]
The only thing that worked for me, to change the 'bottom' style arrow color. Maybe also works for 'top', 'right', and 'left', if you change the names to protect the innocent! ;-)

REACT JS

/* data-class and data-type could be different names, but this works logically for me, to give them the same name of 'customTooltip' */

<span 
  data-class="customTooltip"
  data-type="customTooltip"
  data-tip="Hello World! :-)" >
  <SomeComponent/>
  <ReactTooltip place="bottom"/>
</span>

CSS

/* Change the tooltip's body color */

.customTooltip {
  background: #xyzxyz !important; /* Color of body */
  color: #pqspqs !important; /* Color of text */
}

/* Change the color of the arrow, to match the main body of the tooltip - override the default settings and force your own 'type' of 'customTooltip' into the proceedings... */

.__react_component_tooltip.type-customTooltip.border.place-bottom:before{
  border-bottom:8px solid #xyzxyz !important;
}

.__react_component_tooltip.type-customTooltip.place-bottom:after{
  border-bottom:8px solid #xyzxyz !important;
}
