### ISSUE TITLE
v3.11.2 breaks older implementations

### ISSUE THREAD

**Issue by chrisjpatty** [wwayne/react-tooltip#532]
I don't exactly know what's going wrong here, but I had my package.json setup to lock `react-tooltip` to `^3.3.0`, and our latest yarn builds brought in version 3.11.2, and our long-standing implementation of `react-tooltip` has broken now for unexplained reasons. I've recorded a short video to show the problem:

[http://i.imgur.com/kODN7AI.mp4](url)

I'm afraid I don't have a ton of details about the problem. It happens in every browser where hovering over an element with a tooltip attached no longer shows the element, and instead shifts the layout. I've rolled back my version for now until it can be fixed. Let me know if there's more details I can provide.

**Comment by chrisjpatty** [comment]
With further testing it looks like it's actually been a problem since at least after 3.3.0. Reverting to exactly 3.3.0 fixes the problem. With it being that old perhaps it's as much of an issue, but I figured I'd let you know anyway.

**Comment by Rogger794** [comment]
Hi @chrisjpatty, I would close this issue since should be for old releases. Should be great if you could try the new ones. If you have any issue let us know.
