### ISSUE TITLE
for new developers there should be an easy and well documented way to build the system

### ISSUE THREAD

**Issue by idc-developer** [wwayne/react-tooltip#537]
I have spent quite some time on windows trying to build the system until I found unix make is needed and node/make will not work. For node-sass you need python etc...

Installation should be much easier and only depend on npm and make.

**Comment by Rogger794** [comment]
Now, we are using rollup for build process.

**Comment by Rogger794** [comment]
@idc-developer I would close this issue, since rollup build works fine in windows. Let us know if you try the new release.
