### ISSUE TITLE
Newest release broke clickable tooltips

### ISSUE THREAD

**Issue by josh-stevens** [wwayne/react-tooltip#541]
I can't be too specific at the moment as I'm super busy trying to push a release of our project, but we had tooltips that had interactivity this morning and after the latest release of this library, they stopped working. We pinned to 3.11.2 for now

**Comment by Rogger794** [comment]
Hi @josh-stevens, seems that styles were not updated. I´m rebuilding styles for fixing it.

**Comment by josh-stevens** [comment]
This appears to be working again in 3.11.6, thank you very much
