### ISSUE TITLE
react-tooltip@3.11.4 requires a peer of react@>=^16.0.0

### ISSUE THREAD

**Issue by tonix-tuft** [wwayne/react-tooltip#544]
Hi,

after running `npm update` I get the following warning:

```
npm WARN react-tooltip@3.11.4 requires a peer of react@>=^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tooltip@3.11.4 requires a peer of react-dom@>=^16.0.0 but none is installed. You must install peer dependencies yourself.
```

Though, I have both `react` and `react-dom` at version 16 in my `package.json`:

```
...
    "dependencies": {
        ...
        "react": "^16.12.0",
        "react-dom": "^16.12.0",
        ...
    }
...
```

`package-lock.json`:

```
...
        "react": {
            "version": "16.12.0",
        ...
        "react-dom": {
            "version": "16.12.0",
       ...
...
```

Do you know how to suppress this warning? Thank you!

**Comment by partynikko** [comment]
No need to suppress, it just lets you know that you need to have these installed regardless if you have them or not.

**Comment by tonix-tuft** [comment]
```
... it just lets you know that you need to have these installed regardless if you have them or not ...
```

Thank you for your reply. I didn't know that, I thought that NPM warns you only if you don't have the needed peers installed.
Is this documented somewhere? In my case, I have both `react` and `react-dom` at version 16, I don't get why I keep seeing this warning. I also use other libraries which require `react` as a peer and do not experience the warning with them, that's why I am asking.

Thank you!

**Comment by partynikko** [comment]
> Thank you for your reply. I didn't know that, I thought that NPM warns you only if you don't have the needed peers installed.
> Is this documented somewhere? In my case, I have both `react` and `react-dom` at version 16, I don't get why I keep seeing this warning. I also use other libraries which require `react` as a peer and do not experience the warning with them, that's why I am asking.

I'm no expert at this just referring to my own experiences so I haven't read it somewhere (so perhaps don't take my words about it for granted, haha).

Could it be that this library is being installed before your dependencies and that is why npm is crying about it? Which are the other libraries you use that have peer dependencies as well?

Perhaps we could solve this mystery together, I'm also interested in it :) However I'm quite confident in that it has to do with npm alone.

BR

**Comment by dmozzoni** [comment]
I think the issue might be that in the package.json it says:
```
  "peerDependencies": {
    "react": ">=^16.0.0",
    "react-dom": ">=^16.0.0"
  },
```
but the ">=^"  isn't a valid semver constraint (as far as I can tell). Probably want either ">=" or "^", but not both. Try it in an online semver checker or using the semver package directly.


```
> const semver = require("semver");
> semver.satisfies('16.0.0','>=^16.0.0')
false
> semver.satisfies('16.0.0','^16.0.0')
true
> semver.satisfies('16.0.0','>=16.0.0')
true
> semver.satisfies('16.12.0','>=^16.0.0')
false
> semver.satisfies('16.12.0','>=16.0.0')
true
> semver.satisfies('16.12.0','^16.0.0')
true
```

**Comment by tonix-tuft** [comment]
@dmozzoni So you think this warning is related to the `package.json` of this lib?

**Comment by dmozzoni** [comment]
Yes, I think it's the invalid peerDependencies constraint defined in the react-tooltip package.json file.

To verify this I just created a new folder then did: 
`npm init`
`npm install --save react react-dom react-tooltip`
Got the warning.
`npm install`
Still got the warning, then went to the node_modules/react-tooltip/package.json and removed the caret "^" from the peerDependencies and saved it. Then I tried again.
`npm install`
This time no warning.

This change to react-toolip is relatively recent (Jan 5), probably just a cut-and-paste typo:
https://github.com/wwayne/react-tooltip/commit/bf443deab4d4da83d519c2fb1149666f5b390be8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by partynikko** [comment]
Ah nice find. Sorry for my earlier statement. However I still think that the warning itself doesn't matter for you as it shouldn't affect anything.

**Comment by Rogger794** [comment]
Hi @tonix-tuft, the new release fixed that issue, you can try it.

**Comment by tonix-tuft** [comment]
Thank you guys! No warning now. Closing this issue
