### ISSUE TITLE
NPM version and git tag difference

### ISSUE THREAD

**Issue by mobilutz** [wwayne/react-tooltip#558]
I see that on npm, there is a version [v4.1.0](https://www.npmjs.com/package/react-tooltip). But here on GitHub, there is only a tag [v4.0.4](https://github.com/wwayne/react-tooltip/releases/tag/v4.0.4).

As there is no `v4.0.4` on npm, I think that there is a but with the tag/version. Is that right?

Thanks

**Comment by shepmaster** [comment]
Additionally, the changelog has not been updated for the last few versions.

**Comment by mobilutz** [comment]
Wegen there are correct git tags, then I always use the compare view.

But yes, a changelog is always good to have
