### ISSUE TITLE
Automatically change place when close to screen edge for solid effect

### ISSUE THREAD

**Issue by ahstro** [wwayne/react-tooltip#56]
I was thinking of taking a look at this. Do you have any insight in why the recursion mentioned [here](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L318) happens?

**Comment by wwayne** [comment]
Endless loop, tooltip keeping setState.
I didn't do this for `solid place` mainly because I didn't think it's necessary for `solid`.

**Comment by ahstro** [comment]
Would you welcome a fix? I know it would be useful in my case. :)

**Comment by wwayne** [comment]
of course, welcome PR
