### ISSUE TITLE
Generated UUID in 4.0.5 breaks snapshot testing

### ISSUE THREAD

**Issue by brandon-leapyear** [wwayne/react-tooltip#562]
This commit https://github.com/wwayne/react-tooltip/commit/78e3c2be784f2b96d8bb888b81785b2b38179dae added `generateUUID`, which generates a random UUID every time a tooltip is rendered, which changes Jest snapshots every time they're run.

That commit was done in https://github.com/wwayne/react-tooltip/pull/559, which says "No changes in workflows or documentation", which, while true, apparently didn't take into account changes in the DOM and testing. I would recommend a solution without the `uuid` state, if possible, but if not, some override that would disable the UUID in testing

**Comment by CrOrc** [comment]
It's better to use v4 from npm module uuid to implement generateUUID. Module "uuid" may be mocked in jest for testing. But it's impossible to mock function that is not exported from your module.

**Comment by rathpc** [comment]
@Rogger794  Are there any plans to fix this in an upcoming release?

**Comment by aronhelser** [comment]
Sounds like we have a proposed fix. We would be happy to accept a PR to fix
it.

**Comment by tom1700** [comment]
Hi, I'm afraid the issue still stands. The `uuid` get's bundled together with rest of the code in `/dist/index.js`, which makes it unmockable.

**Comment by rathpc** [comment]
it would be nice if you could just optionally send a flag through the component to override the class. I think this would resolve the problem for snapshots

**Comment by tom1700** [comment]
So it's not nice but it works:
```
jest.mock('crypto', () => ({
  randomBytes: (num: number) => new Array(num).fill(0),
}));

```

**Comment by markph1990** [comment]
Could this be an issue with rollup's config? I don't have experience with this tool, but it seems that we should exclude `dependencies` from our bundle
```js
// rollup.config.js
...
export default {
external: Object.keys(pkg.dependencies || {}),
...
```
or put `uuid` inside `peerDependecies` which then would be automatically excluded via used `rollup-plugin-peer-deps-external`.

**Comment by rathpc** [comment]
my vote is for excluding dependencies or you could simply just exclude uuid, but since there are only two deps in package it is probably ok to do them all.

the single approach would be this:

```js
external: ['uuid']
```
