### ISSUE TITLE
Reposition stopped working going from 3.11.1 to any newer version (3.11.2, 4.x)

### ISSUE THREAD

**Issue by perbergland** [wwayne/react-tooltip#574]
Sample code here:

https://codesandbox.io/s/competent-hooks-bicfv?file=/src/Tooltip.tsx

After upgrading from 3.11.1, I found that tooltips that won’t fit no longer reposition to some other position (top => left, bottom, right). I have tested this in Safari and Chrome on macOS.

```
<ReactTooltip
          className={className}
          id={id}
          effect="solid"
          place="top"        
          type={dark ? "dark" : "light"}
        >
          <div className="tooltip__text">{text}</div>
        </ReactTooltip>
```

Here's what gets displayed with 3.11.1:
<img width="396" alt="Screenshot 2020-04-07 kl  08 34 03" src="https://user-images.githubusercontent.com/2690254/78637946-b59e1b80-78ab-11ea-9515-467ddbd259a4.png">

And with 3.11.2 or newer (in this case 3.11.6)
<img width="417" alt="Screenshot 2020-04-07 kl  08 33 44" src="https://user-images.githubusercontent.com/2690254/78637972-c2227400-78ab-11ea-988f-b7e59153060e.png">

Help?

**Comment by jkonze** [comment]
Same issue here

**Comment by perbergland** [comment]
Here's the diff - what change broke this?

https://github.com/wwayne/react-tooltip/compare/v3.11.1...v3.11.2

**Comment by jkonze** [comment]
@perbergland thanks for pointing out the obvious 😊 

I found the error & will create a Pull Request.

**Comment by perbergland** [comment]
Thanks for the quick response!
