### ISSUE TITLE
ZIndex tooltip

### ISSUE THREAD

**Issue by rullymartanto** [wwayne/react-tooltip#577]
There is away to make tooltip in front of all component / element ?

**Comment by ncastay** [comment]
I started using this component today and had similar issue as you're experiencing.
In my case in Material UI the Drawer component has a zIndex of 1200 which is higher to the zIndex 999 hardcoded in react-tooltip.

However you can overwrite this value using the "data-class" :
`
<MyComponent data-tip data-for={'tooltip'} data-class={classes.tooltip}>
...
</MyComponent>
`
where classes.tooltip has zIndex set to '1500 !important'
