### ISSUE TITLE
Tooltip does not when moving between adjacent elements

### ISSUE THREAD

**Issue by vkbansal** [wwayne/react-tooltip#58]
The tooltip does not work when mouse is moved between adjacent elements with `margin: 0`;
![react-tooltip](https://cloud.githubusercontent.com/assets/5930351/11688886/28dc45ca-9eb5-11e5-99dc-5fcdf300f814.gif)

But Adding a margin between the elements fixes it.
![react-tooltip2](https://cloud.githubusercontent.com/assets/5930351/11688923/5df81d1a-9eb5-11e5-9959-d9b5a0f9bebe.gif)

**Comment by wwayne** [comment]
Should be fixed in 3.0.0
