### ISSUE TITLE
If you open the tooltip and the scroll the window, the tooltip doesn't hide

### ISSUE THREAD

**Issue by scerelli** [wwayne/react-tooltip#59]
Try to open a tooltip and the scroll the window (solid or float). The tooltip stay and doesn't disappear

http://wwayne.com/react-tooltip/

**Comment by scerelli** [comment]
It's pretty easy to handle this bug but i think is not a good behaviour.

anyway this solves the problem:

```
componentDidMount: function() {
    window.addEventListener("scroll", this.hideTooltip);
  },

  componentWillUnmount: function() {
    window.removeEventListener("scroll", this.hideTooltip);
  },

  hideTooltip: function() {
    ReactTooltip.hide();
  }
```

**Comment by wwayne** [comment]
@scerelli 
Thanks, just added scroll event listener when tooltip show and remove the listener after tooltip hide. 
Sometimes the hide action is triggered late, I think it may have something to do with the mechanism of the browser's scroll(or maybe just because my computer is slow...), anyway, I think it's ok

**Comment by Edulopez** [comment]
I think the solution should not close the issue. It looks like a workaround that "fixes" a problem with ` eventOff="blur scroll" `

**Comment by aronhelser** [comment]
The tooltip can be configured to hide or not on scroll. Take a look at the example page for Scrolling.

**Comment by jhlee4** [comment]
I had a problem similar to this, but after further debugging, project that I was working had no window scroll, only element scroll. so none of the solutions above worked.
I managed to fix? it by adding 'onScroll' event on the element that was scrolling
example:
`  public hideUpdateTooltip = () => {
      Tooltip.hide()
    }

    <div onScroll={this.hideUpdateTooltip}>
    //some codes...
   </div>
`

**Comment by linonetwo** [comment]
To use with `react-windowed-list`

```js
import WindowedList from 'react-windowed-list';
import ReactTooltip from 'react-tooltip';
import { useThrottledFn } from 'beautiful-react-hooks';

  const tooltipRefresh = useThrottledFn(
    () => {
      ReactTooltip.hide();
      ReactTooltip.rebuild();
    },
    500,
    null,
    [],
  );
  const renderItem = useCallback(index => {
    tooltipRefresh();
    return <>
...

<ReactTooltip />
<WindowedList
```
