### ISSUE TITLE
DelayShow

### ISSUE THREAD

**Issue by Kadrian** [wwayne/react-tooltip#60]
Hi, I really like this plugin, just wonder why it's not possible to delay (before) showing the tooltip, or is it? Is there a plan to include that at any point?

**Comment by wwayne** [comment]
@Kadrian 
Just create a new feature `delayShow` in v0.9.4
```
<p data-tip="tooltip" data-delay-show='1000'></p> 
or
<ReactTooltip delayShow={1000} />
```
