### ISSUE TITLE
Issue with DelayShow

### ISSUE THREAD

**Issue by dshorowitz** [wwayne/react-tooltip#61]
I just upgraded to 0.9.5 with delay show functionality, but it breaks my code. In the ReactTooltip.prototype.updateTooltip function, the parameter e.currentTarget comes in as expected, but in the delayshowloop, it is null, and therefore no tooltip ever appears. Can you have a look? For now I have downgraded to 0.9.3

**Comment by wwayne** [comment]
Just fixed it, thanks for report.

**Comment by dshorowitz** [comment]
Excellent, thanks!
