### ISSUE TITLE
App netlify is incompatible with React Tooltip 4.2.7

### ISSUE THREAD

**Issue by Puvvl** [wwayne/react-tooltip#615]
I have error at the netlify app `12:26:57 PM: error react-tooltip@4.2.7: The engine "node" is incompatible with this module. Expected version ">=10.18".`

**log:**
`12:25:52 PM: Build ready to start
12:25:56 PM: build-image version: 9d79ad851d6eff3969322d6e5b1df3d597650c41
12:25:56 PM: build-image tag: v3.3.19
12:25:56 PM: buildbot version: 2cc7ea668a3e8f63326d15aab17e62cd1997fa2e
12:25:56 PM: Fetching cached dependencies
12:25:56 PM: Starting to download cache of 302.4MB
12:25:58 PM: Finished downloading cache in 1.470637974s
12:25:58 PM: Starting to extract cache
12:26:12 PM: Finished extracting cache in 14.116406369s
12:26:12 PM: Finished fetching cache in 15.657026512s
12:26:12 PM: Starting to prepare the repo for build
12:26:12 PM: Preparing Git Reference pull/314/head
12:26:15 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
12:26:15 PM: Starting build script
12:26:15 PM: Installing dependencies
12:26:15 PM: Python version set to 2.7
12:26:15 PM: Started restoring cached node version
12:26:18 PM: Finished restoring cached node version
12:26:18 PM: Attempting node version 'v10.13.0' from .nvmrc
12:26:19 PM: v10.13.0 is already installed.
12:26:19 PM: Now using node v10.13.0 (npm v6.4.1)
12:26:19 PM: Started restoring cached build plugins
12:26:19 PM: Finished restoring cached build plugins
12:26:20 PM: Attempting ruby version 2.6.2, read from environment
12:26:21 PM: Using ruby version 2.6.2
12:26:21 PM: Using PHP version 5.6
12:26:21 PM: 5.2 is already installed.
12:26:21 PM: Using Swift version 5.2
12:26:21 PM: Started restoring cached node modules
12:26:21 PM: Finished restoring cached node modules
12:26:21 PM: Started restoring cached yarn cache
12:26:21 PM: Finished restoring cached yarn cache
12:26:22 PM: Installing NPM modules using Yarn version 1.17.0
12:26:22 PM: yarn install v1.17.0
12:26:23 PM: [1/4] Resolving packages...
12:26:23 PM: [2/4] Fetching packages...
12:26:57 PM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
12:26:57 PM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
12:26:57 PM: info fsevents@1.2.12: The platform "linux" is incompatible with this module.
12:26:57 PM: info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
12:26:57 PM: error react-tooltip@4.2.7: The engine "node" is incompatible with this module. Expected version ">=10.18". Got "10.13.0"
12:26:57 PM: error Found incompatible module.
12:26:57 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
12:26:57 PM: Error during Yarn install
12:26:57 PM: Error running command: Build script returned non-zero exit code: 1
12:26:57 PM: Failing build: Failed to build site
12:26:57 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
12:26:57 PM: Finished processing build request in 1m0.751786563s`

**Comment by cameronadams777** [comment]
@Puvvl I believe the issue that you are running into is due to netlify using a version of node for your build that is too low for react-tooltip to be used. That being said, try specifying the version in your `package.json` to avoid this like so: 
```
"engines": {
  "node": ">=10.18.0"
},

```

**Comment by dannykennedy** [comment]
> ```
> "engines": {
>   "node": ">=10.18.0"
> },
> ```
This didn't work for me:(

**Comment by bobf** [comment]
I resolved this by installing `nvm`:
```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```
Then installing Node `10.18.0`:
```bash
nvm install 10.18.0`
```
Finally creating `.nvmrc` in my project directory:
```bash
echo '10.18.0' > .nvmrc
```
And restarting my shell. I was then able to install `react-tooltip`:
```bash
yarn add react-tooltip
```

**Comment by roggervalf** [comment]
Hi all, last release fix this. Hope now works for you.
