### ISSUE TITLE
delayShow not working

### ISSUE THREAD

**Issue by hank7444** [wwayne/react-tooltip#63]
as the title

![image](https://cloud.githubusercontent.com/assets/4727090/11946885/6b98cbf6-a89a-11e5-8326-74ee7b6d105d.png)

**Comment by wwayne** [comment]
@hank7444 
Tested and all works well, could you give me more details if it is still not working for you.

**Comment by miliu99** [comment]
I'm surprised nobody complaint about this anymore...

It's not working if you do <ReactTooptip delayShow={1000}/>.
However, it works if you do <span data-delay-show="1000" data-tip=...
