### ISSUE TITLE
Using without require

### ISSUE THREAD

**Issue by Noitidart** [wwayne/react-tooltip#64]
Hi there,
I'm new to react (and require)
I'm trying to use this from a webpage, not npm.

So I did this:

```
<link rel="stylesheet" type="text/css" media="screen" href="resources/styles/react-tooltip.min.css" />
<script src=resources/scripts/react.min.js"></script>
<script src="resources/scripts/react-dom.min.js"></script>
<script src="resources/scripts/react-tooltip.js"></script>
```

Then I did this:

```
ReactDOM.render(React.createElement('span', {'data-tip':'rawr'}, 'hover me'), myEl);

```

However it does not work, on hover of this element nothing happens. Can you please advise.

**Comment by Noitidart** [comment]
I also tried this but it thorws error that ReactTooltip is not defined. I suspect the require :(  but cant figure that part out

```
React.createElement('span', {'data-tip':'rawr'},
				React.createElement(ReactToolip, {place:"left",type:"dark",effect:"solid"})
)
```

**Comment by wwayne** [comment]
@Noitidart 
sorry, `react-tooltip` doesn't support used by this way. I think it's common for people to use `npm` `browserify` or `webpack` in their projects, so I also didn't have plan to support `webpage load`(actually I don't know how to do it...)

**Comment by Noitidart** [comment]
Ah ok thanks very much for quick reply!
