### ISSUE TITLE
Tooltip goes off-screen if placed over element near screen corner with effect="solid" property

### ISSUE THREAD

**Issue by Firfi** [wwayne/react-tooltip#66]
Hey,

I wonder if it'll be possible implement this. Issue screenshot: (browser window corner is at left)

![screenshot 2015-12-29 14 39 12](https://cloud.githubusercontent.com/assets/947595/12033847/6accacfc-ae39-11e5-97ee-dbb37fbeae20.png)

See how bootstrap implementing it:

![screenshot 2015-12-29 14 43 56](https://cloud.githubusercontent.com/assets/947595/12033899/1321afba-ae3a-11e5-8a8a-97351a0248d3.png)

It moves the content at left side but leaves tooltip triangle over element.

**Comment by Firfi** [comment]
Reproduced here http://codepen.io/Firfi/pen/EPNmya

**Comment by snuderl** [comment]
Same happens to me. Any good workaround?

**Comment by visormatt** [comment]
@snuderl work around I've had to use is positioning on the right side

**Comment by wwayne** [comment]
Currently, react-tooltip will switch to right position in this situation if right position would inside the screen.
