### ISSUE TITLE
Close Tooltip if other get open

### ISSUE THREAD

**Issue by WKStefan** [wwayne/react-tooltip#664]
Hey,

i using your Tooltip for my Project. Now i have one Thing, that is really unfavorable. 

I have nine Buttons with nine other Tooltip-Boxes. Now if i click on one Button the first Tooltip get shown. But if i click now the twoth or fourth Button, than the first Tooltip still shown and the others get shown. So there are many different Tooltip Boxes open. 

Is there a possibility, that the first shown Box get hidden if i click the next Tooltip Button?

**Comment by AlexeyMilenkiy** [comment]
Hi. I faced this problem. I think I was able to resolve it. Please try this.
https://codesandbox.io/s/compassionate-spence-6bnwu?file=/src/App.js

I hope this helps.

```JavaScript
import React from "react";
import ReactTooltip from "react-tooltip";

const elems = Array.from(Array(10).keys());
const tooltipId = `${Math.random()}`;

const Tooltip = React.memo(({ number }) => (
  <div style={{ margin: "50px" }}>
    <button data-tip={tooltipId} data-for={tooltipId} data-event="click">
      Toggle tooltip {number}
    </button>
    <ReactTooltip
      id={tooltipId}
      /**
       * delayHide - this is a solution to the bug of closing the tooltip with a click event.
       * Without it, you will not be able to close the tooltip if you use it several times
       *  */
      delayHide={1}
      event="click"
      globalEventOff="click"
      isCapture={true}
    >
      <span>I am tooltip {number}</span>
    </ReactTooltip>
  </div>
));

export default function App() {
  return (
    <div className="App">
      {elems.map((item) => (
        <Tooltip key={item} number={item + 1} />
      ))}
    </div>
  );
}
```

**Comment by WKStefan** [comment]
Thanks for your help :-) It works now.
