### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

### ISSUE THREAD

**Issue by mmyoji** [wwayne/react-tooltip#667]
This error happens with v4.2.12. https://github.com/wwayne/react-tooltip/issues/665

I thought this was because I didn't add `id` and `data-for` properly to some `react-tooltip` components and target elements, but that didn't solve the issue.

What should I do for it? 

Thanks.

**Comment by mmyoji** [comment]
thank for the quick fix 😄

**Comment by roggervalf** [comment]
Thank you for the quick report

**Comment by janeksmielowski** [comment]
Hi,

Can you provide some further information, why did this happen?

I can see, that you @roggervalf reverted `domRoots.push(parentNode || head)` to `domRoots.push(head || parentNode)`, but right now the tooltips will not work in shadow DOM again. Looking on the whole code, what is the reason to actually find parentNode, when it will never be used:
```
let parentNode = target.parentNode;
while (parentNode.parentNode && !parentNode.host) {
  parentNode = parentNode.parentNode;
}
const head = parentNode.querySelector('head');
domRoots.push(head || parentNode); // if we don't use shadow DOM, here parentNode will always equal to document
```

Maybe this should be replaced with something like this:
```
let parentNode = target.parentNode;
while (parentNode.parentNode && !parentNode.host) {
  parentNode = parentNode.parentNode;
}
const head = document.head;
const  isShownInShadowDOM = !!parentNode.host;
domRoots.push(isShownInShadowDOM ? parentNode : head);
```
Now, it is looking for the shadow root parent node, but when it doesn't find one (means parentNode will equal to `document`), it uses head by default.

Thanks

**Comment by mmyoji** [comment]
Sorry, I didn't give the details.

You can reproduce this with the following commands and code:

```
$ npx create-react-app@4.0.1 myapp --use-npm
$ cd myapp
$ npm i react-tooltip@4.2.12
```

Edit `src/App.js` like this:

```jsx
import Tooltip from 'react-tooltip'

function App() {
  return (
    <div>
      <p data-tip="hello">hello</p>
      <Tooltip />
    </div>
  );
}

export default App;
```

then run `npm start`

React version is v17.0.1
