### ISSUE TITLE
Style tag is not inserted in some conditions

### ISSUE THREAD

**Issue by EASYMOUNTAIN** [wwayne/react-tooltip#669]
Hello there, 

I have an issue with version 4.2.13, so far 4.2.10 works fine.
The <style data-react-tooltip="true"> tag and its content is not inserted in the page <head> after a page refresh.
This happens only in one page though, it seems ReactTooltip doesn't find any roots to insert the style tag in.

This is kind of weird, I cannot really provide an exemple right now, but if needed I'll try to recreate it.

I temporary fixed this bug by adding myself the styles.

Do you have any idea of the cause of the bug ?

Best regards, Olivier

**Comment by DrewHoo** [comment]
I found this too. I installed different versions and saw it was introduced in 4.2.11

**Comment by sumthief** [comment]
Please check 4.2.14. It should fix the problem.

**Comment by Oliv** [comment]
Hello, thanks for the fix, it seems to work fine again !

**Comment by EASYMOUNTAIN** [comment]
Hello, thanks for the fix, it seems to work fine again !
