### ISSUE TITLE
ReactTooltip.rebuild() shows correct tooltip with setState(), but does not hide tooltip from last state value

### ISSUE THREAD

**Issue by sunnydong99** [wwayne/react-tooltip#696]
Hello! I'm having a hard time with a dynamically rendered tooltip in a class component showing the correct text with state change on the page. 
The state is set initially through props:
```
if (this.props.goal == this.props.name){
  this.state = { tipLabel: "TipGoal" }
}
 else if (this.props.hClass == "heartTrue") {
  this.state = {tipLabel: "TipAdd"}
} else {
  this.state = { tipLabel: "TipRemove"};
}
```
This works fine. And the handleAddItem() and handleRemoveItem() functions also change the state accordingly. I know those methods are working fine because the database is updating correctly and I checked the state in console after setState. 
` this.setState({ tipLabel: "TipRemove"})`
For the actual tooltips I am using id and data-for which matches the tipLabel state. I verified through the browser that the data-for of the button is changing correctly onClick, however the tooltip shown didn't change from the initial render data-for.
```
   <ReactTooltip ... id="TipGoal">You can't remove your goal! Change goal first.</ReactTooltip>
   <ReactTooltip ... id="TipAdd" >Add to wishlist</ReactTooltip>
   <ReactTooltip ... id="TipRemove">Remove from wishlist</ReactTooltip>
   <button ... data-tip data-for={this.state.tipLabel} onClick={() => { this.onclickHeart() }}></button>
````
So I added `componentDidUpdate() { ReactTooltip.rebuild(); }`, which now shows the updated tooltip - but also the previous tooltip from initial render, and stays that way - so it always show 2 after 1 click.
![image](https://user-images.githubusercontent.com/65052183/115676010-055b5380-a304-11eb-889d-e90714416010.png)

I've searched through the issues but didn't find a good solution. TIA!

**Comment by ADTC** [comment]
Inside `onclickHeart()` add `ReactTooltip.hide();`.

Or do this: `onClick={() => { ReactTooltip.hide(); this.onclickHeart(); }}`
