### ISSUE TITLE
1.0.0 Cannot read property 'y' of undefined

### ISSUE THREAD

**Issue by SimenB** [wwayne/react-tooltip#70]
After upgrading. When hovering, and the tooltip would normally not be visible in it's default placement, I get a ton of errors.

![image](https://cloud.githubusercontent.com/assets/1404810/12222142/d44aacaa-b7b3-11e5-8713-bd2fabaf564a.png)

The tooltip is also destroyed until a refresh.

Some variables values if it helps: 
![image](https://cloud.githubusercontent.com/assets/1404810/12222187/2ab07114-b7b5-11e5-9758-f39e6c9daab1.png)

`0.9.8` works, but the tooltip is not visible if it clips out out view (which I suppose is what you tried to fix in `1.0.0`)

**Comment by wwayne** [comment]
Fixed in v1.0.2

**Comment by SimenB** [comment]
Sweet, thanks! Works fine now :smile:
