### ISSUE TITLE
div onClick is not firing inside React tooltip container

### ISSUE THREAD

**Issue by narasimhan26** [wwayne/react-tooltip#711]
I am using react tooltip container, where I have a div inside react tooltip container. upon clicking a div it should do some actions. but the facing an issue here seems the onClick listener isn't working inside react tooltip. 

My code sample:

```

const getSomething = () => {
    return (
      <div onClick={() => console.log('Hello world')}>
        Hellow orld
      </div>
    )
  }

<ReactTooltip
    id="actions"
    effect="solid"
    clickable="true"
    className="container"
    globalEventOff="click"
    ref={ref => this.tooltip = ref}>
    {
      getSomething()
    }
</ReactTooltip>
```

The onClick is not firing inside the tooltip container. Let me if I'm missing something. Thanks in advance :))

**Comment by zakariaelas** [comment]
hey @narasimhan26 i'm currently facing the same issue, did you manage to find a workaround?

**Comment by sgurillo** [comment]
@zakariaelas I've tried in different ways your solution but didn't work for me. This is a sample of my tooltip, I want to fire the alert in "My action" button, thank you so much :) 

https://codesandbox.io/s/busy-clarke-xl21f

**Comment by zakariaelas** [comment]
Hey @sgurillo, does this solve your problem https://codesandbox.io/s/gifted-parm-42xel ?

**Comment by sgurillo** [comment]
@zakariaelas yeah it does! Thank you so much dude!
