### ISSUE TITLE
Can you load a page with the tooltip visible?

### ISSUE THREAD

**Issue by mledwards** [wwayne/react-tooltip#739]
I'd like to have the tooltip visible on page load, instead of on click. Is this possible?

I tried using a ref, and then triggering click, but it didn't seem to work.

Thanks!

**Comment by horaczech** [comment]
Works for me when using ref and calling ReactTooltip.show(ref.current) on useEffect with small timeout
`const Tooltip = ({ tip, color }: TooltipProps) => {
    const myRef = useRef<HTMLDivElement | null>(null)
    useEffect(() => {
        if (myRef && myRef.current) {
            setTimeout(() => {
                ReactTooltip.show(myRef.current)
            }, 50)
        }
    }, [myRef.current])
    return (
        <MyTip data-tip={tip} ref={myRef}>
            <TooltipIcon color={color} />
        </MyTip>
    )
}`

**Comment by mledwards** [comment]
Ah nice, I did that but without the timeout! I ended up not using the library and just did an absolutely position tooltip over the relative element, as I didn't need anything from the library. Will remember this in future though!
