### ISSUE TITLE
data-html and html attribute are broken (renders tooltip with "true" as content)

### ISSUE THREAD

**Issue by iandawg** [wwayne/react-tooltip#74]
I'm trying to include HTML content in the tooltip, but instead of rendering the HTML, it renders the word "true" instead of the content provided.

**Comment by richardriman** [comment]
+1

**Comment by wwayne** [comment]
```
<p data-tip='<p>Test html</p>'><p>
<ReactTooltip html>
```
This works for me, how you render HTML content?
