### ISSUE TITLE
When mapping through array, no tooltip showing, although its rendered

### ISSUE THREAD

**Issue by Stophface** [wwayne/react-tooltip#749]
This should be pretty straight forward, but I cannot get it working. I have an array `SHIFTS` through which I loop. For each `shift`, I want to create a `tooltip`. The `tooltip` is showing in the `DOM`, but it is not rendered on hovering...

```
{SHIFTS.map((shift, index) => {
            return <>
              <a
                key={index}
                data-tip
                data-for={`shift-info-${shift}`}>
                <Button
                  clicked={shiftType === shift ? true : false}
                  onClick={() => _onClickShift(shift)}>
                  {shift}
                </Button>
              </a>
              <ReactTooltip
                data-for={`shift-info-${shift}`}
                type='info'
                effect='solid'
                place='right'>
                <span>
                  {shiftText[shift]}
                </span>
              </ReactTooltip>
            </>
          })}
```

**Comment by horaczech** [comment]
You have to specify the text (data-tip='tip text'), currently you have data-tip an empty string.

**Comment by Stophface** [comment]
@horaczech That is not helping. I changed it to

```
<>
                <a
                    key={index}
                    data-tip={shiftText[shift]}
                    data-for={`shift-info-${shift}`}>
                    <Button
                        disable={disable}
                        clicked={shiftType === shift ? true : false}
                        onClick={() => _onClickShift(shift)}>
                        {shift}
                    </Button>
                </a>
                <ReactTooltip
                    data-for={`shift-info-${shift}`}
                    type='info'
                    effect='solid'
                    place='right' />
            </>
``` 

and no luck... Still no tooltip.

**Comment by horaczech** [comment]
I got it working like this now with only rendering <ReactTooltip /> once (and only) on the page and without data-for attribute. This may be the case of multiple ReactTooltips and data-for: https://github.com/wwayne/react-tooltip#3-tooltip-not-binding-to-dynamic-content.  I hope this helps.
```
{SHIFTS.map((shift, index) => {
            return <>
              <a
                key={index}
                data-tip={shiftText[shift]}>
                <Button
                  clicked={shiftType === shift ? true : false}
                  onClick={() => _onClickShift(shift)}>
                  {shift}
                </Button>
              </a>
            </>
          })}
          <ReactTooltip
              type='info'
              effect='solid'
              place='right' />
```

**Comment by horaczech** [comment]
I for example use the ReactTooltip component only once for the whole project in App.js and only add data-tip (data-place, data-offset) attribute to desired elements/components, when unified styling is OK.

**Comment by Stophface** [comment]
@horaczech The example you posted did not work like this, but with the hint to the documentation I was able to solve it:

{SHIFTS.map((shift, index) => {
            return <>
              <a
                key={index}
                // This is the text content of the tooltip
                data-tip={shiftText[shift]}
                // This must be the same as id in <ReacTooltip />
                data-for='sreference-for-tooltip'>
                <Button
                  clicked={shiftType === shift ? true : false}
                  onClick={() => _onClickShift(shift)}>
                  {shift}
                </Button>
              </a>
            </>
          })}
          <ReactTooltip
              id='reference-for-tooltip'
              type='info'
              effect='solid'
              place='right' />
