### ISSUE TITLE
Mount/Unmount memory leak

### ISSUE THREAD

**Issue by AlexGalays** [wwayne/react-tooltip#76]
```
window.removeEventListener('__react_tooltip_hide_event', this.globalHide)
window.addEventListener('__react_tooltip_hide_event', ::this.globalHide, false)
```

Since `::this.globalHide` creates a new bound function, `window.removeEventListener('__react_tooltip_hide_event', this.globalHide)` will effectively do nothing.

These fonctions should probably be bound once and for all with that ES stage-X feature :  `globalHide = () => {}`

**Comment by wwayne** [comment]
Fixed, thanks :+1:
