### ISSUE TITLE
ReactTooltip.hide doesn't hide tooltip instantly

### ISSUE THREAD

**Issue by erezcarmel** [wwayne/react-tooltip#765]
I'm trying to create a tooltip using `react-tooltip` with a close button. According to the [documentation](https://github.com/wwayne/react-tooltip#reacttooltiphidetarget), I need to use `ReactTooltip.hide` but it doesn't seem to work. It hides the tooltip only if I'm moving the cursor out of the tooltip, but not instantly.

Using React 17.0.2, react-tooltip 4.2.21.

Here's a quick [CodeSandbox](https://codesandbox.io/s/hidden-star-er2u66) example to see my issue.

**Comment by xclark-harriscomputer** [comment]
Also seeing the same issue, using React 16.12.0 and react-tooltip 4.2.21.

**Comment by svmszcck** [comment]
As a quick fix you can do this until the package is updated:

```
const [tooltip, showTooltip] = useState(true);

<>
 {tooltip && <ReactTooltip effect="solid" />}
 <p
   data-tip="hello world"
   onMouseEnter={() => showTooltip(true)}
   onMouseLeave={() => {
     showTooltip(false);
     setTimeout(() => showTooltip(true), 0);
   }}
 />
</>
```

**Comment by erezcarmel** [comment]
> As a quick fix you can do this until the package is updated:
> 
> ```
> const [tooltip, showTooltip] = useState(true);
> 
> <>
>  {tooltip && <ReactTooltip effect="solid" />}
>  <p
>    data-tip="hello world"
>    onMouseEnter={() => showTooltip(true)}
>    onMouseLeave={() => {
>      showTooltip(false);
>      setTimeout(() => showTooltip(true), 50);
>    }}
>  />
> </>
> ```

Great quick fix @svmszcck 
Thanks.

**Comment by dfalt** [comment]
Has a fix for this been prioritized or released in some way? I don't mind using the workaround, but it would be nice to be able to follow an issue that will resolve the problem in a release as this one has been closed.
