### ISSUE TITLE
How can I tell ReactTooltip to search for data-tips again after they are hidden and unhidden?

### ISSUE THREAD

**Issue by Hypaethral** [wwayne/react-tooltip#77]
This relates to https://github.com/wwayne/react-tooltip/issues/44.  I tried using ReactTooltip.rebuild() as suggested in that issue to no avail.  I am using version 1.0.4 of react-tooltip.

Code structure, no css:
```js
var CollapsibleBox = React.createClass({
  getInitialState: function() {
    return {
      collapsed: false
    };
  },
  toggleCollapse: function() {
    this.setState({collapsed: !this.state.collapsed})
  },
  render: function() {
    if (this.state.collapsed) {
      return (
          <h1> {this.props.title} <span onClick={this.toggleCollapse}>open</span>
          </h1>
      );
    }
    return (
        <div>
          <h1> {this.props.title} <span onClick={this.toggleCollapse}>close</span>
          </h1>
          {this.props.children}
        </div>
    );
  }
});

var UserIcon = React.createClass({
  // when hovering on a userIcon, the user's name should always display
  render: function() {
    //for simplicity, instead of an image, the UserIcon just displays its id instead
    return (
        <div data-tip={this.props.name}>
          <p>{this.props.id}</p>
        </div>
    );
  }
});

var App = React.createClass({
  render: function() {
    return (
        <div id="app">
          <CollapsibleBox title="Box1">
            <UserIcon name="George Gumbo" id="1"/>
            <UserIcon name="Dave Graves" id="2"/>
          </CollapsibleBox>
          <CollapsibleBox title="Box2">
            <UserIcon name="George Gumbo" id="1"/>
            <UserIcon name="Dave Graves" id="2"/>
            <UserIcon name="Larry Nidorf" id="3"/>
          </CollapsibleBox>
         <ReactTooltip />
        </div>
    );
  }
});

ReactDOM.render(
    <App />,
    document.getElementById('container')
);
```
Fiddle with css to help visualize box setup (does not include react-tooltip at this time): https://jsfiddle.net/sk6ak97k/

Desired Behavior:  My app will have many collapsible informational boxes with UserIcons which display an image.  On hover, these user images should display a user's name in a ReactTooltip.

Reproduce unwanted behavior: Close box1 and then open it.  Until a UserIcon from box2 is hovered, the UserIcons from box1 lose their tooltip.

Question:  It seems react-tooltip is not rebuilding its collection of data-tips on each rerender (this is a good thing!), but how can I force it to do so whenever a collapsibleBox is uncollapsed?  I've tried ReactTooltip.rebuild() as suggested in issue 44.  Is there a better solution to this unwanted behavior?

**Comment by wwayne** [comment]
@Hypaethral In your situation, it is correct to use `ReactTooltip.rebuild()`, I did some experiment based on your example:
```
toggleCollapse: function() {
   this.setState({collapsed: !this.state.collapsed}, function () {
      ReactTooltip.rebuild()
   })
}
```
Rebuild tooltip after setState works on my side, rebuild ReactTooltip won't re-render DOM, so it won't reduce your application's performance.

**Comment by Hypaethral** [comment]
Thank you for verifying -- knowing this was the correct solution, I moved some components around.  In my actual code, it seems ReactTooltip was being rendered too high up in my render tree.  Moving it down closer to the CollapsibleBox like in my example code fixed the issue.

**Comment by wwayne** [comment]
@Hypaethral I would like to put one `<ReactTooltip />` in one page, for those components that need tooltip, just adding `data-tip` attribute to it, that's ideal situation of its usage.

If you happen to put several `<ReactTooltip />` in one page, you had better using `id` and `data-for` to mark them in case repetition.
