### ISSUE TITLE
React can't find the root component node for data-reactid value - it probably means you've loaded two copies of React on the page

### ISSUE THREAD

**Issue by dodekeract** [wwayne/react-tooltip#78]
I get a quite similar error to #48. However I think mine has a different reason.

I included react-dom via `<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.2/react-dom.min.js" charset="utf-8" crossorigin="anonymous"></script>`.

This package doesn't detect or expect that ReactDOM is a globally available variable. And I think this leads to it requiring `react-dom`.

The reasons why I use CDNs for react-dom are:
1. server load (less data to transmit)
2. build speed (doesn't take ~3 seconds to build every time...)

PS: Sorry for the inital title fuck-up, I accidentally hit enter when editing the title. :cry:

**Comment by wwayne** [comment]
@dodekeract 
`react-dom` can support server rendering: `require('react-dom/server')`, https://www.npmjs.com/package/react-dom.
As for build speed, I've tried rendering react in server side, I think it's ok for me, maybe you can take a try on `react-dom/server`.

**Comment by dodekeract** [comment]
I don't server-render. The whole app lives on the client. But since it's using JSX, I need to compile that first. This step takes some seconds less when I use CDNs instead of npm packages for react & react-dom.

**Comment by wwayne** [comment]
Did some fix, could you take a try again, version: 1.0.6

**Comment by dodekeract** [comment]
Sure, just a moment.

**Comment by dodekeract** [comment]
Didn't seem to fix the issue.

**Comment by wwayne** [comment]
@dodekeract After referring to other react components, I build a standalone js file. So now you can import  `standalone/react-tooltip.min.js` in your page header(after react and react-dom), then using `ReactTooltip` directly in your component.
I don't know if this is a good way for your using, because you have to grab the file `standalone/react-tooltip.min.js` out of `node_modules/`. I just did some small test, not in your project.
You can take a try and any advice is welcome.

**Comment by dodekeract** [comment]
Sounds good, thanks, will test that tomorrow.

**Comment by dodekeract** [comment]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: module "./style" not found from "/home/dodekeract/code/manta-config-engine-app/node_modules/react-tooltip/standalone/react-tooltip.min.js"
    at notFound (/home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/index.js:803:15)
    at /home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/index.js:754:23
    at /home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
    at /home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:36:22
    at load (/home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:54:43)
    at /home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:60:22
    at /home/dodekeract/code/manta-config-engine-app/node_modules/gulp-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by dodekeract** [comment]
Works completely fine, when manually copying `style.js` from `dist/` to `standalone/` though.

**Comment by wwayne** [comment]
Humm, yes I missed a file.
Closing the issue, thanks.
