### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by bermi** [wwayne/react-tooltip#82]
Are there plans to support fastclick touch devices?

Right now in order to show a tooltip the user has to touch and hold (which emulates the mouse events).

I need to add support for displaying the tooltip on touchstart on an application that uses react-tooltip. @wwayne Before starting coding and sending a PR that could be merged back into this project I'd like to know if you had suggestions on what the correct UX would be.

**Comment by wwayne** [comment]
@bermi This component has an attribute called `event` which can set the way of show/hide tooltip by **Click**, I don't know if this is what you need.
Also, I supposed that you would like to show the tooltip by clicking the screen first, then the tooltip can hidden by itself after a period of time. If so, you can use `delayHide`

**Comment by bermi** [comment]
Thanks for the info about "data-event" @wwayne, you should probably change "customer event" on the readme to "custom event", that got me confused initially :)

Anyhow I believe that the "fastclick" issue we are having with touch and hold might have something to do with our integration of react-tooltip or some other side effects unrelated to this library, since I don't see the same happening on the react-tooltip demo page.
