### ISSUE TITLE
Calculate outside position for solid effect

### ISSUE THREAD

**Issue by andrejunges** [wwayne/react-tooltip#83]
I think we should calculate the outside positions for `solid` effect as well..
We dont have to follow the mouse position (of course) but is there a case why we shouldn't considerate the outside positions for it?
![screen shot 2016-03-07 at 1 38 19 pm](https://cloud.githubusercontent.com/assets/5039334/13575900/e7ecc314-e469-11e5-95ff-ba89594cd7c0.png)

**Comment by wwayne** [comment]
Hi @andrejunges , what do you mean by saying `calculate the outside positions`? I guess it is: for example, if the tooltip in top is out of the web page, it should be changed to bottom position automatically.

**Comment by andrejunges** [comment]
exactly @wwayne

**Comment by andrejunges** [comment]
was there a reason to not implement it? @wwayne

**Comment by wwayne** [comment]
@andrejunges No, just because no time for this at the moment, may do some trying this weekend.

**Comment by wwayne** [comment]
Thanks @andrejunges, support from 1.1.4
