### ISSUE TITLE
A hover tooltip feature?

### ISSUE THREAD

**Issue by itsNikolay** [wwayne/react-tooltip#85]
Should we add "a hover tooltip feature", when a tooltip does not disappear on its hover?
It's useful to place an interactive content into the tooltip.

**Comment by wwayne** [comment]
I think you are looking for something like this:

you can combine using the feature `class` and `delayHide` of react-tooltip to achieve this:
```
<a data-tip="tooltip" data-class="extra" data-delay-hide="500"></a>
<ReactTooltip />

.extra {
 &:hover {
   visibility: visible !important;
   opacity: 1 !important;
 }
}
```

**Comment by itsNikolay** [comment]
great, it works! 
I would add it in README
thanks!

**Comment by wwayne** [comment]
That would be great, thanks
