### ISSUE TITLE
Data-event click, clicking several tooltips leaves all visible instead of the current one.

### ISSUE THREAD

**Issue by bbricegno** [wwayne/react-tooltip#89]
When several tooltips are instantiated on a single page, the data-event click doesn't act fully as a toggle to hide all active tooltips. Not sure if this is the desired behavior but it would make sense that only the current tooltip be activated at a time.

**Comment by visormatt** [comment]
Have you tried firing ReactTooltip.hide() on the click to close all instance?

**Comment by bbricegno** [comment]
On the version 1.2.0 the prop: eventPropagationMode was introduced. Changing the event propagation mode to 'capture' solved this issue.

**Comment by VanDavv** [comment]
Issue still occurs, please reopen
