### ISSUE TITLE
"dataset" and IE

### ISSUE THREAD

**Issue by af7** [wwayne/react-tooltip#9]
Please read what it says here:

http://stackoverflow.com/questions/23034428/having-problems-in-ie8-when-attempting-to-get-data-from-target-event

It appears that the use of "dataset" causes problems for IE10 and below. 
Would you consider fixing this? (if it a problem at all)

Thx.

**Comment by wwayne** [comment]
@af7 Fixed.
Really thanks for your information :+1:
