### ISSUE TITLE
Errors: "Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bradennapier** [wwayne/react-tooltip#91]
I am running into an error where it will say 'Cannot read property length of null' when i hover over an area which has a null value (for example when dynamically generating he tooltips).

This appears to happen when you are within the "updateTooltip" function if (this.trim(this.state.placeholder).length > 0) (something similar to that).

Every time I hover any element in my tables now it gives that error unless a tooltip is present... to my knowledge on the components which cause the error there is no tooltip even rendered as a prop so it seems to be a logic error somewhere.

**Comment by wwayne** [comment]
Hmm, so if I am not misunderstanding. In your situation, you have an element that switch between `data-tip='xxx'` and `data-tip=''`, and you will get error when there's no content in `data-tip`

**Comment by wwayne** [comment]
Should be fixed in 3.0.0
