### ISSUE TITLE
need bower support

### ISSUE THREAD

**Issue by dispareil** [wwayne/react-tooltip#97]
I was trying to install this package with bower. Couldn't install the package. Always got  

ECONFLICT Unable to find suitable version for react-tooltip

**Comment by wwayne** [comment]
The package only support NPM and standalone(you can find js file in standalone folder, then use `<script src="....">` to import the file)

**Comment by mikkopiu** [comment]
@wwayne: would it make sense to have a `bower.json` with the standalone script as the `main` file?

That way this package could be easily used with tools like [wiredep](https://github.com/taptapship/wiredep) that automatically scan through Bower dependencies' main files (and often add them to `index.html` or similar). 

I'd be happy to make a PR for this.

**Comment by wwayne** [comment]
@mikkelvagn Sure you can send me a PR because I'm not using bower and unfamiliar with that.

**Comment by mikkopiu** [comment]
Created PR: https://github.com/wwayne/react-tooltip/pull/179
